nqminds/edgesec

docs/docusaurus/docusaurus.config.js
On GitHub Pages, this documentation will be hosted on:
https://nqminds.github.io/EDGESec/
This means we need to set `baseUrl` to `/EDGESec/`
=> Fix docusuarus baseUrl

CMakeModules/install.cmake, debian/changelog, debian/control, debian/edgesec-mdnsf.install
Not tested yet on a Raspberry Pi, so that's still todo.
=> Create `edgesec-mdnsf.deb` debian file

tests/ap/CMakeLists.txt
Fixes the current failing CI/CD run in the `main` branch:
https://github.com/nqminds/EDGESec/runs/4550634608?check_suite_focus=true
=> Include missing `sqlite3.h` in `test_ap_service`

docs/docusaurus/docs/devices.md
Documents the unsupported devices that @mcr discovered in #87, #88, #89, #90, and #91
I've added @mcr as a co-author, since they did most of the work!
This is what the table looks like on the website:
=> Document known unsupported USB modems

CMakeLists.txt
Modern versions of the GCC compiler default to using `-std=gnu11`, but it's good to explicitly state this in the CMakeLists.txt file, so that an error will be thrown if the compiler is too old to support C11.
We explicitly allow GNU C compiler extensions, since we use `strncasecmp` in `hostapd` and `libnetlink`, which isn't part of standard C. (side-note, this means that compiling with LLVM/clang probably won't work)
=> Use C11 to compile C code

docs/docusaurus/docs/capture.md
This issue was caught by prettier!
See discussion in https://github.com/nqminds/EDGESec/pull/107#discussion_r846126245
=> Fix incorrect markdown table in capture docs

docs/docusaurus/docs/compilation.md
Doing `mkdir build/ && cd build/ && cmake ..` is the old way of using cmake and isn't great for a few reasons:
- Firstly, your script may fail if the folder already exists
- Secondly, you're jumping around using `cd` which isn't great
- Thirdly, if you want to build using ninja or a different build system, `make` will not work, but `cmake --build build/` will work!
=> Use new `cmake -B` or `cmake --build` CLI

lib/pcap.cmake
We don't use PCAP with netlink support, so we might as well disable it to make static linking easier.
See https://github.com/nqminds/EDGESec/pull/106#discussion_r847275828 for discussion.
=> Disable compiling PCAP with netlink support

.github/workflows/create-debs.yml
Now that we're a public repo, GitHub Actions CI is now free, so we can increase some of our limits since we're not paying for it anymore.
This includes:
- Boosting `.deb` artifact retention to 7 days
- Running CI on GitHub's public runners.
- Each run is slightly slower, but we get basically infinite runs in parallel. Plus, they're much more secure since they're not on our local virtual machines.
- Since we get infinite runs in parallel, I've set up CI to run on every `git push`, not just when a PR should be merged.
=> CI improvements now that we're a public repo

.github/workflows/create-debs.yml
Currently, all the debs are being built in the `/var/cache/pbuilder/result` folder, which isn't great, as all of the old results are stored there too.
This meant that month-old `.deb`'s were also being uploaded as GitHub Action artefacts.
This change instead places it in [`runner.temp`](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context), which is a folder that GitHub Actions clears between each run.
=> ci: Build `.deb` in temp directory

debian/rules
=> Remove redundant CMake defines from debuild

lib/uci.cmake
Locks the libuci/lububox dependencies to a specific git commit.
This is to make repeatable builds, as any future commits in these repos won't change the behaviour.
Unfortunately, git still uses SHA1 hashes, so attacks such as SHAttered can still be used to do supply-side attacks, even with a commit hash.
I've disabled `GIT_SHALLOW`, since is not possible when `GIT_TAG` for a commit. However, I think these repos are pretty small, so it shouldn't take much longer to `git pull` everything.
GitWeb, which is what the OpenWRT repos use, supports `.tar.gz` downloads (https://git.openwrt.org/?p=project/libubox.git;a=snapshot;h=1087eaf77ae2f5e25d58b4550608f6c65de7d15d;sf=tgz), but they're built on demand, which means we can't use a URL_HASH to make sure that we're always downloading the same file.
=> Lock uci/ubox dependencies to specific git commit

CMakeModules/EdgesecInstallLocations.cmake, CMakeModules/InstallConfigFile.cmake, config.ini.in, debian/changelog
Fixes a few bugs for the `config.ini` file in debian builds 
Our config path was being installed as `/usr/etc/edgesec/config.ini`, when it should be `/etc/edgesec/config.ini`
(bug discovered in https://github.com/nqminds/EDGESec/pull/107)
This was because when calling the CMake macro, `GNUInstallDirs_get_absolute_install_dir`,
as we didn't specify it was a `SYSCONFDIR` (i.e. `/etc`), it automatically
prepended `usr/`, as stated in the CMake GNUInstallDirs special cases:
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#special-cases
According to the GNU coding standards,
the $DESTDIR environment variable should **NOT** be used
be stored in any file contents
https://www.gnu.org/prep/standards/html_node/DESTDIR.html
This was causing issues with the config.ini file in .deb …
=> Fix wrong deb location for etc/edgesec/config.ini

README.md
This is to hide the ugly red badge and replace them with nice green ones.
=> Fix broken CI badges on README.md

.pre-commit-config.yaml, CMakeLists.txt, CMakePresets.json, README.md, docs/docusaurus/docs/compilation.md
Currently, manually defining all the different EDGESec defines for each platform is quite complicated.
The new [cmake-presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) feature in new versions of CMake makes this a lot easier, by allowing us to pre-define some presets.
Essentially, as long as you have CMake v3.22.0 or greater, you can do the following to configure/build/test easily:
```bash
cmake --preset linux # configure EDGESec for Linux in a ./build/linux folder
cmake --build --preset linux -j4 # build EDGESec for Linux using 4 threads
ctest --preset linux # test EDGESec for Linux
```
=> Add `cmake-preset` for Linux

.gitmodules, deployment/first-boot/README.md
[nqm-ssh-tunnel](https://github.com/nqminds/nqm-ssh-tunnel) is a private NQMinds Git repo, and having it as a git submodule is breaking code that expects EDGESec to be fully public (e.g. using OpenWRT SDK to build EDGESec)
=> chore: remove nqm-ssh-tunnel as a git submodule

docs/docusaurus/docs/compilation.md
Instead of duplicating the documentation for Ubuntu/Debian compilation dependencies, we can just use [`mk-build-deps`](https://manpages.ubuntu.com/manpages/focal/man1/mk-build-deps.1.html) to automatically install the dependencies listed in `debian/control`.
=> docs: improve Ubuntu/Debian dependency docs

CMakeModules/CMakeToolchains/openwrt-21-ath79-generic.cmake, CMakeModules/CMakeToolchains/openwrt-ath79-generic.cmake, CMakePresets.json
Add support for compiling for ath79/generic on OpenWRT 19.07.10
Try it out with `cmake --preset openwrt/ath79/generic` and `cmake --build -j4 --preset openwrt/ath79/generic`
The https://openwrt.org/toh/hwdata/tp-link/tp-link_eap225-outdoor_v1 is not currently supported, as it requires at least OpenWRT 21.02.
I'm currently trying to download the OpenWRT 21.02 SDK, but the office internet is slow, so it's going to take a while.
=> build(ath79/generic): support ath79/generic

src/ap/CMakeLists.txt, src/capture/CMakeLists.txt, src/dns/CMakeLists.txt, src/dns/mdns_service.c, src/supervisor/CMakeLists.txt, src/utils/CMakeLists.txt, tests/supervisor/CMakeLists.txt
Adds missing CMake library definitions.
I've added a CMake definition for some header-only libraries too, like ap_config.h and capture_config.h, as since they require utils/os.h, they need to link to the os.c lib.
=> build: fix cmake library definitions

debian/copyright
Adds copyright info and licensing info from files in `src/utils` and `src/radius`.
=> Add copyright info for `src/utils` and `src/radius`

src/supervisor/cmd_processor.h, src/supervisor/crypt_commands.h, src/utils/os.c, src/utils/os.h, tests/supervisor/test_cmd_processor.c, tests/utils/test_os.c
A lot of the mocked `cmd_processor` functions were mocked to return `OK_REPLY`.
Then, the tests were checking to make sure that exactly `strlen(OK_REPLY)` bytes were written.
However, https://github.com/nqminds/EDGESec/commit/260584216ba1eefd0bb9d7c2ca6c9e4dbc5a7a35 added a newline to many writes, so instead we need to check for `strlen(RESULT "\n")`.
=> Fix failing `cmd_processor` tests

src/crypt/crypt_service.c, src/crypt/crypt_service.h, src/crypt/sqlite_crypt_writer.c, src/crypt/sqlite_crypt_writer.h, src/supervisor/crypt_commands.c, src/supervisor/crypt_commands.h
The data pointed to by `keyid` and `blob` are read-only, so we should declare it as `const`.
We can always undo it if we need to, but C will warn us first.
Added while I was debugging https://github.com/nqminds/EDGESec/pull/162
=> refactor: make `sign_blob_cmd` args `const`

.github/workflows/create-debs.yml, CMakePresets.json
Currently, none of our CI attempts to build or run the crypto service.
This adds a preset for it, so that it is tested correctly.
=> ci: add build/test preset for crypto service

.github/workflows/pages.yml, docs/doxygen.cmake
Publish doxygen docs to GitHub Pages.
If the CMake variable `-DBUILD_ONLY_DOCS=ON`, then CMake throws an error if it can't find `doxygen` or graphviz's `dot` (used to create the directional graphs in doxygen).
=> Publish doxygen docs to nqminds.github.io/edgesec

CMakeLists.txt, docs/doxygen.cmake, src/ap/CMakeLists.txt, src/capture/middlewares/cleaner_middleware/CMakeLists.txt, src/capture/middlewares/header_middleware/CMakeLists.txt, src/capture/middlewares/pcap_middleware/CMakeLists.txt, src/crypt/CMakeLists.txt, src/dhcp/CMakeLists.txt, src/dns/CMakeLists.txt, src/firewall/CMakeLists.txt, src/radius/CMakeLists.txt, src/supervisor/CMakeLists.txt, tests/CMakeLists.txt, tests/ap/CMakeLists.txt, tests/capture/CMakeLists.txt, tests/crypt/CMakeLists.txt, tests/dhcp/CMakeLists.txt, tests/dns/CMakeLists.txt, tests/radius/CMakeLists.txt, tests/supervisor/CMakeLists.txt, tests/system/CMakeLists.txt, tests/utils/CMakeLists.txt
Working on #177
Btw, it looks like the standard practice for naming projects in CMake is CamelCase, e.g. https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_VERSION.html#variable:CMAKE_PROJECT_VERSION
Is it worth us naming the CMake project `Edgesec` instead? (I'll be honest, it looks very weird to me, but it might be worth it just to make it consistent with the rest of the CMake world)
=> Rename CMake project from `EDGESEC` to `edgesec`

debian/rules
If there is only a single package in `debian/control`, by default, the `debian/*.install` files do nothing, since everything is installed by default.
This PR overrides `dh_auto_install` so that the same behaviour is used, whether building multiple packages or just the one.
Should fix this failing CI action: https://github.com/nqminds/edgesec/runs/7149699032?check_suite_focus=true
=> build(debian): fix debian build when single out

tests/capture/CMakeLists.txt
My fault, I forgot commans weren't allowed in cmake files, and I didn't see the warning that cmake printed.
=> build: remove invalid comma in test/capture cmake

README.md, docs/doxygen.cmake, docs/mainpage.dox
Adds the README.md file to the doxygen website, and links to it from the doxygen homepage.
This is what the new doxygen homepage will look like:
=> Include README.md in docs

docs/doxygen.cmake
Currently, there are 84 nodes in the include diagram for src/utils/os.h and we need to manually increase the limit if we want it to render.
After increasing the limit, we can see this very ~spaghetti-like~ beautiful diagram by looking at https://nqminds.github.io/edgesec/os_8h.html 
I mainly increased the limit to hide the warning that Doxygen printed.
=> build(docs): bump DOT_GRAPH_MAX_NODES to 128

docs/doxygen.cmake
SVGs are smaller, text can be copy-and-pasted from, they can be zoomed in indefinitely, and best of all, the boxes are hyperlinks to their docs page.
=> build(docs): build dot files as SVGs, not PNGs

src/capture/capture_service.h, src/capture/middlewares/header_middleware/mdns_decoder.h, src/capture/middlewares/header_middleware/packet_queue.h, src/capture/middlewares/pcap_middleware/pcap_queue.h, src/crypt/sqlite_crypt_writer.h, src/dns/mdns_mapper.h, src/dns/mdns_service.h, src/firewall/firewall_service.h, src/supervisor/crypt_commands.h, src/supervisor/network_commands.h, src/supervisor/sqlite_macconn_writer.h, src/utils/cryptou.h
Fixes some more doxygen errors.
I was bored waiting for stuff to compile, so while I was waiting, I fixed the rest of the Doxygen errors.
It looks like all the remaining Doxygen errors are from `eloop.h` or `src/radius/*`, which use a different non-Doxygen documentation system ([kernel-doc](https://docs.kernel.org/doc-guide/kernel-doc.html)).
=> Fix some more doxygen errors

.github/workflows/create-debs.yml
Fixes the non-existing cmake preset in the CI tests.
Fixes: https://github.com/nqminds/edgesec/commit/8c3090a85ec21de8fee94df59db4751a5bb1f641
=> ci: fix non-existing cmake preset

lib/sqlite.cmake
Reverts sqlite3 to v3.31.01 as that's the version supported by Openwrt 19.07.
=> build(sqlite3): revert sqlite3 to v3.31.01

README.md
Adds the following badges:
Currently, the GitHub release badges don't show anything, since https://github.com/nqminds/edgesec/releases is empty.
Fixes #171
[![GitHub release (latest stable SemVer)](https://img.shields.io/github/v/release/nqminds/edgesec?label=stable&logo=github&sort=semver)](https://github.com/nqminds/nqm-ssh-tunnel/releases)
[![Build Debian Packages](https://github.com/nqminds/edgesec/actions/workflows/create-debs.yml/badge.svg)](https://github.com/nqminds/edgesec/actions/workflows/create-debs.yml)
[![GitHub release (latest SemVer including pre-releases)](https://img.shields.io/github/v/release/nqminds/edgesec?include_prereleases&label=latest&logo=github&sort=semver)](https://github.com/nqminds/nqm-ssh-tunnel/releases)
[![GitHub …
=> docs: add open-source badges

.github/workflows/pages.yml
GitHub Pages now accepts being deployed directly from GitHub Actions, so we no longer need a `gh-pages` branch.
See https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/
=> ci(docs): use new github-pages CI action

.github/workflows/create-debs.yml, Dockerfile, README.md
Our `debian/control` file has all the files required to build edgesec on a Debian PC. We should use this to control all dependency management.
=> Use `debian/control` to install dependencies

.github/workflows/create-debs.yml
Both the arm64 and amd64 code had the same cache key and were conflicting with each other.
=> ci(deb): fix caching in pbuilder base

src/dhcp/CMakeLists.txt, tests/CMakeLists.txt
Make skips compiling tests when cross-compiling, so you will only encounter this error when compiling for x86_64 OpenWRT.
The issue was that `test_runctl.c` could not find "uci.h".
Adding `supervisor_config` as a dependency to `test_runctl` adds UCI to the include paths when needed.
(I also fixed the `dnsmasq` bit, since that had a linking error too)
=> build(openwrt): fix broken tests for OpenWRT

lib/hostapd.cmake
Bump hostapd to v2.10 instead of just using a git commit.
Support was added for OpenSSL 3.0 in hostapd v2.10, so we could try doing something with that too.
Full release notes are at:
https://lists.infradead.org/pipermail/hostap/2022-January/040148.html
=> chore(deps): bump hostapd to v2.10

README.md
Adds even more open-source badges for:
- [![Documented with Doxygen](https://img.shields.io/badge/docs-Doxygen-blue.svg?foo&bar)](https://edgesec.info/doxygen/)
Links to https://edgesec.info/doxygen/, aka the page with the doxygen iframe.
- [![GitHub Pages](https://github.com/nqminds/edgesec/actions/workflows/pages.yml/badge.svg)](https://github.com/nqminds/edgesec/actions/workflows/pages.yml)
Links to https://github.com/nqminds/edgesec/actions/workflows/pages.yml, e.g. the status of the GitHub Pages CI action
Although, we might be moving into the territory of too many open-source badges.
=> docs: add badges for doxygen C docs

.github/workflows/create-debs.yml
I'm not very smart! I never actually tested whether the `.deb`'s created by GitHub were accurate.
It looks like by not passing a `data` param, the the data just became a JSON string of the file, so the size looked right, but it was useless data.
E.g., instead of the `.deb` file on the https://github.com/nqminds/edgesec/releases pages being real `.deb`s, they were just strings of `"file":{"type":"Buffer","data":[33,60,97,114,99,104,62,10,100,...`
According to the official GitHub API docs, the actual field name is `data`: https://octokit.github.io/rest.js/v18#repos-upload-release-asset
=> ci(publish): fix incorrect Debian data

debian/control
`jq` isn't used anywhere in edgesec
=> fix(debian): remove unused dependency on `jq`

.github/workflows/create-debs.yml
The focal .deb is incompatible with jammy, due to the libssl1.1 package being missing, as it was replaced with libssl3.
The only part of the edgesec that was using OpenSSL was:
- the bundled hostapd
- when compiled with `USE_CRYPTO_SERVICE=true`
As hostapd v2.10 is compatible with OpenSSL 3.0.0 (see #216), and `USE_CRYPTO_SERVICE=false` is normally disabled, upgrading the OpenSSL 3.0.0 shouldn't cause any disruption.
**Note**: In order to prevent the focal (Ubuntu 20.04) and jammy (Ubuntu 22.04) packages from having the same filenames, I changed the `.deb`s to have the filename pattern: `name_version_distribution_arch.deb`, so that `distribution` was included in the filename.
=> ci(debs): build for ubuntu 22.04 jammy

debian/changelog
pdebuild and debuilder were printing out a lot of errors (again and again) about how the changelog was incorrect.
=> style(deb): fix `debian/changelog` formatting

debian/edgesec.service
The `-s` option only makes sense if edgesec is compiled with `USE_CRYPTO_SERVICE=true`, which it isn't normally. Using it now results in the error: `Command-line usage error: Unrecognized option -s`
=> fix(debian): remove `-s` opt from edgesec service

tests/crypt/CMakeLists.txt
`tests/crypt` is only included if `USE_CRYPTO_SERVICE` is true, so it should be fine to run tests, even if `BUILD_OPENSSL_LIB` is false (it may be false if OpenSSL is already installed,  e.g. Ubuntu 22.04 already comes with OpenSSL 3.0)
=> test: test crypt_service if `USE_CRYPTO_SERVICE`

.github/workflows/create-debs.yml, CMakeLists.txt, CMakePresets.json, debian/copyright
It seems like the `CMake/CodeCoverage.cmake` file wasn't being used, so I quickly added a GitHub Action for it.
Currently, the coverage action runs after all tests pass, since it only makes sense to check coverage if tests pass. I've also kept it as a separate `cmake` action, as it requires `lcov`, which is not normally installed by people.
=> Add code coverage GitHub Action

tests/capture/test_capture_service.c
Tests fail when repeated since the `/tmp/edgesec` folder already exists.
=> test: handle case where `/tmp/edgesec` exists

CMakePresets.json, src/utils/sqliteu.c, src/utils/sqliteu.h, tests/crypt/CMakeLists.txt, tests/crypt/test_crypt_service.c, tests/utils/CMakeLists.txt, tests/utils/test_sqliteu.c
Adds CI tests for `linux-with-crypt`.
After adding these tests, I found that the tests were failing, since the `prepare_find_table` function was failing to find the `store` database, due to an `SQLITE_MISUSE` error.
I did a bit of refactoring to simplify the function and add error handling and the function and tests seem to work now.
**Draft until #227 is merged**
=> Fix failing WITH_CRYPT_SERVICE test

CMakeLists.txt, CMakeModules/CMakeToolchains/DefineOpenWRTSDKToolchain.cmake, lib/hostapd.cmake, lib/openssl.cmake, lib/sqlite.cmake
On CMake v3.24.0, edgesec currently prints the following warning multiple times:
```
CMake Warning (dev) at /snap/cmake/1147/share/cmake-3.24/Modules/ExternalProject.cmake:3071 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
robustness issue.
```
By setting …
=> Fix CMake CMP0135 configure warning

.github/workflows/create-debs.yml, CMakeLists.txt
Prints the output of the test if a ctest test fails.
This will help with debugging failing CI tests.
=> ci: output on ctest failure

tests/utils/test_os.c
Adds tests to add full code-coverage to the function `make_dirs_to_path`.
Function docs are here, if you want to know what this function is supposed to do https://nqminds.github.io/edgesec/os_8c.html#ab45d38138784ebb93e2eafbc4b20fbf0
@AshleySetter, no pressure if you don't want to review this :) It's not anything urgent, it's just I wanted to add full test coverage for this function since I was the one that added the function.
=> Fully test `make_dirs_to_path()`

tests/utils/test_os.c
Adds a test case for `string_append_char` when the input string is null.
=> test: test for NULL string in string_append_char

.github/workflows/create-debs.yml, CMakePresets.json, src/utils/uci_wrt.c, tests/CMakeLists.txt, tests/ap/CMakeLists.txt, tests/ap/test_hostapd.c, tests/dhcp/CMakeLists.txt, tests/dhcp/test_dnsmasq.c, tests/utils/CMakeLists.txt, tests/utils/__wrap_uwrt_init_context.c
Runs the OpenWRT tests in CI.
I had to slightly play around with some stuff to get OpenWRT tests working again.
Firstly, I had to add `LD_LIBRARY_PATH="${sourceDir}/build/${presetName}/lib/ubox/lib"`, see https://github.com/nqminds/edgesec/commit/ee360ebd6e586790c86fdc0245b54690519eb522 to get OpenWRT tests working properly, since even though we set RPATH on our tests, since the tests link to libuci, libuci is the one that needs RPATH to libubox.
This meant I had to modify the CI to use the presets listed in CMakePresets.json (see [ci: use buildDir from CMake presets](https://github.com/nqminds/edgesec/commit/df4bd607c8e66af522c62ef97321e37c3d4590ed)), then I had to add a preset for `openwrt` that set `LD_LIBRARY_PATH` (see [ci: add test config for …
=> Test OpenWRT in CI

CMakeLists.txt, debian/control, debian/rules, lib/pcap.cmake, lib/sqlite.cmake, src/CMakeLists.txt, src/capture/CMakeLists.txt, src/capture/capture_service.c, src/config.c, src/dns/CMakeLists.txt, src/edgesec.c, tests/capture/middlewares/CMakeLists.txt, tests/dhcp/test_dhcp_service.c, tests/dhcp/test_dnsmasq.c, tests/dns/test_command_mapper.c, tests/dns/test_mdns_list.c, tests/dns/test_mdns_mapper.c, tests/dns/test_mdns_service.c, tests/dns/test_reflection_list.c, tests/utils/CMakeLists.txt
Currently, libsqlite3 and libpcap are statically linked to edgesec, even when building a `.deb`.
Dynamic linking speeds up compilation, makes our package smaller (both on disk and in memory), and means sqlite3/libpcap can be updated to fix bugs without our package being updated.
The dynamically linked version of libsqlite3 is exactly the same as the statically linked version.
**However, the current statically linked version of libpcap is 1.10.1, which is newer than the dynamically linked libpcap 1.9.1** It seems to compile and run tests fine, though, so it probably means we aren't using any new libpcap features.
=> build(debian): link to sqlite3/libpcap shared libs

README.md
Adds the following badge to the README.md to show that we follow the LLVM code style: [![code style: llvm](https://img.shields.io/badge/code%20style-LLVM-green?logo=llvm&color=2b617a)](https://llvm.org/docs/CodingStandards.html)
=> docs: add a "code-style LLVM" badge

tests/CMakeLists.txt, tests/ap/CMakeLists.txt, tests/capture/CMakeLists.txt, tests/capture/middlewares/CMakeLists.txt, tests/crypt/CMakeLists.txt, tests/dhcp/CMakeLists.txt, tests/dns/CMakeLists.txt, tests/supervisor/CMakeLists.txt
Instead of manually setting LINK_FLAGS for each target, we can use CMake's [target_link_options][1].
This has a few benefits:
- args can be scoped to be `INTERFACE|PUBLIC|PRIVATE`
- args are automatically deduplicated
- linker flags are portable for all compilers
(e.g. these options will work both for Clang and GCC)
Downsides:
- Minimum CMake support is v3.13, which is fine, since our project minimum is currently v3.14
[1]: https://cmake.org/cmake/help/latest/command/target_link_options.html
=> build: convert LINK_FLAGS to target_link_options

.github/workflows/create-debs.yml
Limit the `create_debs.yml` action to the bare minimum permissions it needs to runs the actions.
This is considered to be more secure, as it lowers the risk of supply-side attacks getting access to our GitHub repo.
=> ci: limit `create-debs.yml` permissions

.clang-format, src/radius/radius_server.h
On FreeBSD, `#include <netinit/in.h>` should come before `#include <netinit/if_ether.h>`, as otherwise `struct in_addr` won't be defined.
I've modified the `.clang-format` rules so that after #116 gets merged, this shouldn't cause any issues.
=> refactor: change netinit/in.h #include order

.github/workflows/create-debs.yml
GitHub Actions CI tests are failing intermittently due to an SQLite `Failed to execute statement: disk I/O error`.
I'm pretty sure this is due to some sort of race condition, either with:
- a) our thread code
- b) GitHub Actions file-system
This commit adds a `sleep 5` between the CI tests and the coverage tests in an attempt to prevent this error.
Fixes https://github.com/nqminds/edgesec/issues/252 (hopefully at least!)
=> ci: fix intermittent disk I/O error

src/capture/middlewares/header_middleware/dns_decoder.c, src/capture/middlewares/header_middleware/mdns_decoder.c, src/capture/middlewares/header_middleware/packet_decoder.c, src/capture/middlewares/header_middleware/packet_decoder.h
Including `<netinet/ip.h>` is causing issues on FreeBSD.
These includes aren't actually needed, so we might as well get rid of them and speed up compilation slightly.
=> refactor: remove unnecessary middlewares includes

src/radius/radius.h, src/radius/radius_server.c, src/radius/radius_server.h, tests/radius/ip_addr.h, tests/radius/radius_client.c, tests/radius/radius_client.h, tests/radius/test_radius_server.c
As far as I'm aware, this doesn't do anything, except cause issues on non-Linux platforms like FreeBSD.
=> refactor: remove `#include <asm/types.h>`

lib/cmocka.cmake
For non-Windows targets, CMocka v1.1.5 only works for 32-bit or 64-bit GNU libc targets.
The latest upstream master branch contains commit https://gitlab.com/cmocka/cmocka/-/commit/0e70150002ab7bcb626109b287f23c62ecf97565, which adds CMocka support for 64-bit muslibc and for Cheri ARM/Morello/128-bit pointers.
=> build: bump cmocka to latest master commit

tests/dhcp/test_dnsmasq.c
These functions return `int`, and `error_t` is only a Linux type, and not supported on FreeBSD.
=> test: remove incorrect error_t type

src/radius/wpabuf.h
Cleans up the `wpabuf.h` file to improve support for non Linux OSes like FreeBSD.
As of glibc 2.19, the following macros are defined in `endian.h`:
```
htobe16(), htole16(), be16toh(), le16toh(), htobe32(), htole32(),
be32toh(), le32toh(), htobe64(), htole64(), be64toh(), le64toh()
```
These macros are also defined in FreeBSD, however they are located in the `<sys/endian.h>` file.
=> refactor(wpabuf): simplify byte swaps

src/capture/middlewares/header_middleware/packet_decoder.c
Refactors the `packet_decoder` so that the POSIX standard values for the `udphdr` and `tcphdr` struct are used.
On Linux, these structs are defined as a union, so that the POSIX standard can also be used. However, other platforms like FreeBSD only have the POSIX standard.
=> refactor: use POSIX standard udphdr/tcphdr

.clang-format, src/radius/radius_server.h, tests/radius/radius_client.c
On FreeBSD, `#include <sys/socket.h>` must be included before including `#include <netinet/in.h>`.
=> refactor: include sys/socket.h then netinet/in.h

tests/utils/test_os.c
My fault, I accidentally wrote `const` instead of `char`, and C implicitly assumed that it was an `int` pointer.
Maybe it's worth setting `-Werror` in our code so that all C warnings become errors.
=> test: fix invalid test variable type

src/utils/nl.c, src/utils/nl.h
The `subnet_mask` is never modified, so we can convert it to a `const char *` and make our life easier.
This fixes a compiler warning.
=> refactor(nl): mark subnet_mask param as const

src/dhcp/dnsmasq.c, src/dhcp/dnsmasq.h, tests/dhcp/test_dnsmasq.c
When creating new interfaces from the `wifi_interface` + `vlanid`, ensure that we always keep the full `vlanid` in the new interface name, by truncating the `wifi_interface`/`interface_prefix` to the appropriate number of bytes.
Since the max vlanid is 4094, and interface names are usually limited to 16 bytes, we need to limit the interface_prefixes to 11 bytes.
Fixes `src/dhcp/dnsmasq.c:87:37: warning: ‘snprintf’ output may be truncated before the last format character` compiler warnings.
=> fix(dnsmasq): truncate interface names/prefix

tests/utils/test_os.c
test_run_command tries to run `/bin/uname`.
However, on FreeBSD, `uname` is instead located in `/usr/bin/uname`.
A cross-platform way of calling uname is to instead use the `/usr/bin/env` command.
=> test(os): standardize test_run_command test

docs/doxygen.cmake
Enables the [`OPTIMIZE_OUTPUT_FOR_C`][1] Doxygen option.
It basically just renames the list of classes to a list of "Data Structures", since C does not have classes.
[1]: https://www.doxygen.nl/manual/config.html#cfg_optimize_output_for_c
=> docs: optimize doxygen docs for C code

.github/workflows/create-debs.yml
The GitHub Actions cache step keeps on freezing and taking 6 hours to crash.
I've made the following commits in an attempt to fix this:
- [ci(deb): limit cache download step to 10 minutes](https://github.com/nqminds/edgesec/commit/78ec74b84c03083b305be1f6ff1d344c88762592)
- [ci(deps): bump actions/cache from v2 to v3](https://github.com/nqminds/edgesec/commit/ba2676128158b5ff186f6662d69c3f53e2c44085)
Also, I've noticed that sometimes the cache doesn't work properly due to a permissions error.
Because of that, I've added [ci(deb): fix cache permissions error](https://github.com/nqminds/edgesec/commit/572406ca66a682138eb1bdff5517ecc76b463672) in this PR too.
=> Improve the GitHub Actions cache step

tests/utils/test_ifaceu.c
On FreeBSD, the loopback interface is not called `lo`.
Instead, it is called `lo0`.
I've also removed a bunch of [unnecessary includes](https://github.com/nqminds/edgesec/commit/80bb8d9acec7ef0601840ba8c015e3193ada8973)
=> Fix ifaceu test on FreeBSD

tests/supervisor/test_sockctl_server.c
It's probably easier to review each commit one by one!
The main point of this PR is to remove the use of `tempnam` from this project, as it is deprecated and the compiler/linker throws a warning on use.
The first line of the description in the [tempnam manpage](https://manpages.ubuntu.com/manpages/jammy/en/man3/tempnam.3.html) says:
> _Never use this function_.  Use mkstemp(3) or tmpfile(3) instead.
I've also used `teardown()` functions to automatically cleanup all of the sockctl temporary files, so that my `/tmp` folder isn't filled with junk! 
In commit [test(sockctl): refactor and cleanup tests](https://github.com/nqminds/edgesec/commit/77e6fd332cfe1d55698e6c1788eb717e655c5f11), I've also done some general cleanup.
=> Cleanup sockctl tests

src/utils/os.h, tests/utils/test_os.c
test_run_command() expects that the output of `uname -s` is always "Linux\n". However, this isn't right for two reasons:
- That string isn't guaranteed to be NUL-terminated, so one day it might instead be `Linux\n<some_junk_data_here>`.
- On other platforms like FreeBSD, `uname -s` does not print Linux.
Because of this, I've changed the test command to print "Hello World!", and to handle the NUL-terminator and some other stuff.
=> Standardise `test_run_commands` test

src/capture/middlewares/cleaner_middleware/cleaner_middleware.c, src/capture/middlewares/pcap_middleware/pcap_middleware.c
`ltype` was made const in commit 669377818af88075f604e71224a703820e30704b but some middlewares missed the change.
Fixes: 669377818af88075f604e71224a703820e30704b
=> refactor(middlewares): fix const stype difference

tests/radius/radius_client.c
Casting a pointer to an int is not well defined.
However, casting a pointer to a `uintptr_t` is perfectly legal. Then, casting a `uintptr_t` to a smaller `int`/`enum` is also perfectly legal (although it may result in a loss of data).
The only issues is that `uintptr_t` might not exist on every platform, but it probably exists on all the big platforms.
=> refactor(radius_client): fix ptr to enum cast

tests/utils/test_os.c
The `if()` check was previously broken and not doing anything. (`test_state->tmp_dir` is an array in a struct, so it will never be `NULL`).
=> test(os): fix broken make_dirs_to_path teardown

tests/capture/middlewares/test_packet_queue.c
Initialises a variable so we don't get an uninitialised warning.
=> test(packet_queue): fix uninitialised warning

src/utils/nl.c
According to the indentation, this was supposed to be part of the if-block, but because there were no curly braces, the auto-formatter reformatted it.
See https://github.com/nqminds/edgesec/blob/8cd691957f4b727f81d08a0e452caf22102de317/src/utils/nl.c#L1058-L1060
Fixes: 3c1e6da64d9e0d2dad383dbff737d0353f44321e
=> fix(nl): fix missing curly brackets

tests/supervisor/test_bridge_list.c, tests/utils/test_iface_mapper.c
Replaces all usages of:
- `assert_int_equal(memcmp` with [`assert_memory_equal()`](https://api.cmocka.org/group__cmocka__asserts.html#gac933d8b75ebd55e88ca85963721c05d9)
- `assert_int_equal(strcmp` with [`assert_string_equal()`](https://api.cmocka.org/group__cmocka__asserts.html#ga3db7885581668648088fc4eb4cee6d4f)
=> Better CMocka asserts

tests/capture/middlewares/CMakeLists.txt, tests/capture/middlewares/test_sqlite_header.c
The `test_sqlite_header` test is intermittently failing in GitHub Actions.
I'm not 100% sure why this the test is failing.
One thing I did notice is that CMocka performs really poorly in multi-threaded applications.
As recommended in the CMocka docs, I've added the `CMOCKA_TEST_ABORT=1` environment variable so that CMocka automatically `aborts()` if a test fails, see https://api.cmocka.org/#main-threads
I've also removed all of the `assert_*()` macros from the non-main threads, since CMocka doesn't properly handle these. Instead, we pass an error_message string to the main thread, and the main thread then calls `asssert_string_equal()` on it.
This might fix https://github.com/nqminds/edgesec/issues/252, but even if it doesn't, hopefully this will improve the logs and make it easier to …
=> test(sqlite_header): improve sqlite_header tests

src/utils/os.c, src/utils/os.h, tests/utils/test_os.c
C programs such as `run_command()` accept argv as an `char *`, not a `const char *`. This is because the `main()` function of programs is explicitly allowed to modify the data in `argv()`.
This can cause issues, since we declare arrays using string literals, (e.g. `char * argv[] = {"hello", "world", NULL};`), and modifying string literals is undefined behaviour.
To get around this, we can just make a mofiiable copy of argv before passing it to run_command().
There is a warning we can enable that will check for this (`-Wwrite-strings`), but it creates 100s of warnings throughout our code-base, so it's something we should slowly fix.
=> feat(os): add copy_argv() function

src/ap/ap_service.c, src/dns/mdns_service.c, src/utils/CMakeLists.txt, src/utils/sockctl.c, src/utils/sockctl.h, tests/supervisor/CMakeLists.txt, tests/supervisor/test_sockctl_server.c
Currently, [`create_domain_client(NULL)`](https://nqminds.github.io/edgesec/sockctl_8c.html#ab74693481cda01c302ed453c910a4096) creates a new temporary _abstract_ Unix domain socket:
> **Abstract sockets**
>
> [...]
> Abstract sockets automatically disappear when  all  open  references  to  the  socket  are closed.
>
> The abstract socket namespace is a nonportable Linux extension.
(from https://manpages.ubuntu.com/manpages/jammy/en/man7/unix.7.html)
Since abstract sockets are "a notportable Linux extension", they are not supported by FreeBSD.
Because of this, I've instead replaced this code with creating a new _pathname_ Unix domain socket, where the socket is located in `/tmp/edgesec.XXXXXX/client-socket.sock`, where `/tmp/edgesec.XXXXXX` is made with `mkdtemp`.
**By default, this code …
=> Add fallback for unsupported abstract sockets

src/utils/nl.c
When compiling with `-DCMAKE_BUILD_TYPE=Release`, we get a `-Wstringop-truncation` warning.
This is because when `strncpy` exits early because the input string is too long, it **DOES NOT** copy a NUL terminator. Instead, we need to manually setup a NUL terminator ourselves.
---
Side-note, I've been trying to use NULL to denote `NULL` (aka ptr type) and NUL/␀ to denote `'\0'` (aka char/byte type). That seems to be the convention for C programmers.
=> fix(nl): fix potential missing NUL terminator

src/utils/sockctl.c
Store temporary unix domain socket dirs in the `/tmp/edgesec/` folder, as this is where other temporary edgesec files are stored.
The full mkdtemp template is now `/tmp/edgesec/tmp-unix-socks.XXXXXX`
=> refactor(sockctl): store tmp sock in /tmp/edgesec

src/CMakeLists.txt, tests/CMakeLists.txt, tests/utils/test_os.c
Enables the GCC/Clang `-Werror` flag on everything in the src/ and tests/ folder.
It's only enabled if `-DCMAKE_BUILD_TYPE=Debug`. This is so that any 3rd parties using edgesec (for example https://github.com/nqminds/manysecured-openwrt-packages or even the `.deb` build) should still be able to compile edgesec, even if they have a newer version of GCC/Clang that adds new warnings.
These warnings are usually pretty useful, so we probably want to fix them all. If we ever want to disable this, we can do:
```cmake
add_compile_options(-Wno-error=foo) # too many -Wfoo warnings
```
Or better yet, we can use [`target_compile_options`](https://cmake.org/cmake/help/latest/command/target_compile_options.html) to disable them just in one file:
```cmake
target_compile_options(my_library_with_warnings …
```
=> Error on all C/C++ compiler warnings in `src/` and `tests/`

src/utils/sockctl.c
Whoops, I forgot that `sizeof("")` includes a NUL-terminator, even though `strlen("")` does not include a NUL-terminator.
=> fix(sockctl): fix cleanup of unix mkdtemp dirs

CMakeLists.txt, tests/utils/test_eloop_threaded.c
pthreads.h is non-standard C11.
The C11 `threads.h` library is supported in almost every modern C11 compiler. However, since it's technically optional, we should explicitly check if it's supported, so that we can print a nicer error message.
Technically, the way you are supposed to do this is by checking for `__STDC_NO_THREADS__`, but that's not easy to do in CMake.
On Linux, you must still link with -lpthreads.
However CMake's `find_package(Threads)` means that we can just link to `Threads::Threads` and CMake will auto-link the correct threading library.
The API for `threads.h` and for `pthreads.h` is pretty similar, but:
- pthread.h behaviours slightly different on Linux from baseline POSIX.
- [cppreference](https://en.cppreference.com/w/c/thread) is much nicer than looking at Linux man …
=> Replace pthread with threads in `test_eloop_threaded`

docs/doxygen-tag-files.cmake, docs/doxygen.cmake
[cppreference.com][1] supplies a Doxygen tag file that can be used to automatically link standard C functions/types to the appropriate cppreference page.
Unfortunately, the tag file is for the C++ stdlib, not the C stdlib, however, the C standard library is mostly included in the C++ spec.
For example, `va_list` will link to https://en.cppreference.com/w/cpp/utility/variadic/va_list, which the C++ version of https://en.cppreference.com/w/c/variadic/va_list
See [the doxygen TAGFILES option][2].
[1]: https://en.cppreference.com/w/Cppreference:Archives#Doxygen_tag_file
[2]: https://www.doxygen.nl/manual/external.html
This slows down the `doxydocs` build by about 1 second, so the performance impact is minimal.
=> docs: link to cppreference.com in doxygen docs

tests/utils/CMakeLists.txt, tests/utils/test_eloop.c, tests/utils/test_os.c, tests/utils/tmpdir.c, tests/utils/tmpdir.h
Removes the usage of `tempnam()`, which is deprecated and throws a warning on use.
The first line of the description in the tempnam manpage says:
> _Never use this function_.  Use mkstemp(3) or tmpfile(3) instead.
I've made a new file called `tests/utils/tmpdir.h` that contains the following functions, that can be used as CMocka setup/teardown functions.
- `int setup_tmpdir(void **test_state);`
- `int teardown_tmpdir(void **test_state);`
=> Remove deprecated `tempnam()` from eloop tests

.github/workflows/create-debs.yml
Adds a job that builds the recap exe using `-DCMAKE_BUILD_TYPE=Release` (aka `-O2`/`-O3`) and uploads it as a build artifact.
Additionally, it will upload the `recap` exe as a release artifact on GitHub releases.
=> ci(recap): add an job that builds the recap exe

.github/workflows/create-debs.yml, CHANGELOG.md, CMakeLists.txt
**Draft until #300 and #301 are merged**
Adds a v0.1.0-alpha.0 pre-release.
See `CHANGELOG.md` for all the changes in the v0.1.0-alpha.0 pre-release.
The main new feature is adding the `recap` executable, to save captured packets to SQLite db from a pcap file or from an input stream.
=> Pre-release v0.1.0-alpha.0

src/utils/CMakeLists.txt, src/utils/hashmap.c
We don't need to `#include <os.h>` or `#include <allocs.h>` since these functions are part of the C11 standard lib.
strdup() is also part of the C23 standard, but it's part of the POSIX standard too.
The only annoying thing is that although `strnlen_s` is part of the C11 standard. Everybody hates it, and only MSVC has these functions (although they're meant to be buggy).
Luckily, `strnlen_s` is very easy to define in terms of `strnlen`, which is part of the POSIX standard, and part of GCC/Clang's stdlib (the only difference is that `strnlen_s` returns 0 if the input str is `NULL`)
=> refactor(hashmap): fix circular dependency

src/utils/iptables.c, src/utils/iptables.h, src/utils/net.c, src/utils/net.h
Modifying string literals is undefined behaviour in the C spec, and can cause all sorts of trouble (especially at higher optimisation levels).
A good way to prevent modifying string literals is to label them as `const`. This is the default behaviour in C++, but unfortunately, back in the early days of C, `const` didn't yet exist, and so we need to add an optional `-Wwrite-strings` compiler flag to enable making them `const` by default.
While waiting for OpenWRT to super slowly compile, I went through the `iptables` source files and made sure that we had no `-Wwrite-strings` warnings.
=> Refactor non-`const` string literals in `iptables`

src/radius/radius.c
Fix `-Wwrite-strings` warnings, where we use a string literal in a non-const location.
=> refactor(radius): fix `-Wwrite-strings`

src/firewall/firewall_service.c, src/runctl.c, src/utils/hashmap.c, src/utils/hashmap.h, src/utils/iptables.c, src/utils/iptables.h, tests/system/test_system_checks.c, tests/test_runctl.c, tests/utils/test_hashmap.c
Set the params and return value of `hmap_str_keychar_get()` to `const`.
Also, there's no point in making the `hmap` param a pointer-to-a-pointer if we never modify the pointer, we might as well just pass a pointer and get a performance boost, simplify code, and make it more obvious that we're not changing anything.
Benefits:
- Reduces the risk of modifying string literals (undefined behaviour by the C compiler)
- Makes it unlikely for us to accidentally modify hash_maps using the get function.
- Improves usage documentation
- Performance increase, since we're moving from a `**` to a `*` (pointer to pointer to just a pointer) (the compiler might have optimized this with Link-time-optimization)
=> Make `hmap_str_keychar_get()` params const

.github/workflows/create-debs.yml
The GitHub codecov upload action keeps on failing, and recommends setting a CODECOV_TOKEN.
Technically, we shouldn't need one, since we're using a public repository, but it might be that we're encountering some sort of usage limit, so setting an explicit `CODECOV_TOKEN` might help.
=> ci(coverage): use codecov token from CODECOV_TOKEN

.github/workflows/create-debs.yml, CMakePresets.json, src/utils/ipgen.c, src/utils/ipgen.h
Test the `IP_GENERIC_SERVICE` using GitHub Actions.
Currently, the only CMake preset that uses the `IP_GENERIC_SERVICE` is `recap`, so I've added a CTest preset for it too, so that we can run `IP_GENERIC_SERVICE` tests and to get coverage results.
Additionally, I've fixed the `const` errors in `ipgen` that were preventing `recap` from compiling.
=> Test the IP_GENERIC_SERVICE using GitHub Actions

src/runctl.c, src/utils/hashmap.c, src/utils/hashmap.h, src/utils/os.c, src/utils/os.h
Prevents modifying string literals in `runctl`, by making sure that all functions that use string literals are const (e.g. following `-Wwrite-strings`).
Additionally, I had to make a copy of string literals whenever we pass them to a function that might modify them (e.g. run_process() or basename()).
After this PR (and the other open ones), I managed to fully compile the `--preset openwrt` when `-Wwrite-strings` without any errors! This means we shouldn't have any undefined behaviour due to modifying strings in OpenWRT.
=> Prevent modifying string literals in `runctl`

src/utils/uci_wrt.c
Fix `-Wwrite-string` warnings in uci_wrt.
We don't modify any string constants in the `uci_wrt` code, so we might as well make everything `const` to ensure we don't modify any string constants.
This prevents `-Wwrite-string` from raising any warnings.
=> refactor(uci_wrt): fix `-Wwrite-string` warnings

src/crypt/crypt_service.c, src/crypt/crypt_service.h, src/crypt/sqlite_crypt_writer.c, src/crypt/sqlite_crypt_writer.h, src/utils/cryptou.c, src/utils/cryptou.h
Fix `-Wwrite-string` warnings when running `cmake --preset linux-with-crypt`.
We don't modify any string constants in the `crypt` code, so all we had to do was to make some params `const`.
This prevents `-Wwrite-string` from raising any warnings.
=> Fix `linux-with-crypt` `-Wwrite-string` warnings

src/utils/eloop.c, src/utils/eloop.h
This function is not used anywhere, so we might as well delete it.
=> refactor(eloop): remove `eloop_wait_for_read_sock`

tests/utils/CMakeLists.txt, tests/utils/test_eloop_handles_null.c
Test whether eloop functions correctly return -1 and log an error message if their `struct eloop_data *eloop` param is NULL.
Instead of duplicating the test 8 different times, I've used [X Macros](https://www.drdobbs.com/the-new-c-x-macros/184401387) to automate it.
My feeling is that it's cleaner than duplicating the code 8 times in 2 different places, even if it does use some crazy C pre-processor macros of macros.
=> test(eloop): test handling NULL `eloop` param

tests/CMakeLists.txt
The uci_wrt tests sometimes modify the `./tests/data/uci` files. This causes issues with `git switch`/`git rebase`.
This commit means we instead test on a copy of the test data in the build directory.
=> test(uci_wrt): use temporary test data files

CMakeLists.txt, CMakeModules/AddCMockaTest.cmake, debian/copyright, tests/CMakeLists.txt, tests/ap/CMakeLists.txt, tests/capture/CMakeLists.txt, tests/capture/middlewares/CMakeLists.txt, tests/crypt/CMakeLists.txt, tests/dhcp/CMakeLists.txt, tests/dns/CMakeLists.txt, tests/radius/CMakeLists.txt, tests/supervisor/CMakeLists.txt, tests/system/CMakeLists.txt, tests/utils/CMakeLists.txt
Uses the `AddCMockaTest.cmake` script from the CMocka library to simplify building and adding tests.
Because it's only a build script (it's not a statically-linked executable), we don't need to add licensing information to the `edgesec` software under the BSD 3-Clause license.
Adds the `AddCMockaTest.cmake` helper script from https://gitlab.com/cmocka/cmocka/-/blob/a7a1ae83d567ccd6b469e157fc0a3db872039a49/cmake/Modules/AddCMockaTest.cmake
Add licensing and copyright information for AddCMockaTest.cmake
It uses the BSD 3-Clause license.
Use the AddCMockaTest.cmake script to simplify the test CMake build scripts.
By default, all `LINK_LIBRARIES` are linked privately by default, since the tests are executables and are not expected to be linked to by other CMake targets.
There is a …
=> Use `AddCMockaTest.cmake` script to simplify test scripts

.github/workflows/create-debs.yml, lib/mnl.cmake, lib/openssl.cmake, lib/protobuf-c.cmake, lib/sqlite.cmake, lib/uuid.cmake
Ninja is much faster than GNU Make, and is now the default CMake generator for OpenWRT, see https://github.com/openwrt/openwrt/commit/0c7c24d40aedcee25d5243e25a87d38246be128b.
This PR adds support for compiling edgesec using Ninja.
Currently, all of our `ExternalProjects` using `make` are using `$(MAKE)` so that their builds are run in the same `make` invocation as the main repo.
(e.g. this means things like multiprocessing get shared with all ExternalProjects).
However, this does not work when the main project is using a non-Makefile generator.
Instead, I've changed the CMake files to use `make` when not running in a Makefile generator.
Unfortunately, this change actually means that build edgesec with Ninja is **slower** than using GNU Make. This is because then the ExternalProjects have …
=> Add support for compiling edgesec using Ninja

debian/copyright
Document the `lib/cmocka.cmake` file in `debian/copyright`. It's available under the Expat/MIT license, and was taken from https://github.com/OlivierLDff/cmocka-cmake-example/blob/f11cb0eb5ab4b0bde5df400888c5d17b6882bd97/cmake/FetchCMocka.cmake
=> docs(lib/cmocka.cmake): document licensing info

debian/copyright
Document that `tests/radius/radius_client.*` is licensed under the BSD-3 Clause.
=> docs(radius_client): document licensing info

.github/workflows/create-debs.yml
Since https://github.com/nqminds/edgesec/pull/338/commits/f66d46573a6af577bdbfb2529d8372c63b82633d, CMake downloads are now downloaded into `build/dl` by default, which makes caching the downloads much easier.
=> ci: cache `cmake/dl` folder

src/dns/mcast.c, src/radius/radius_server.c, tests/radius/radius_client.c
Some functions (e.g. `radius_client_disable_pmtu_discovery()`) are no-ops on platforms that are missing Linux (or Darwin) specific features.
This is normally fine, except we have `-Wunused` and `-Werror` enabled, so an error is thrown for unused varaibles.
This commit casts them to `(void)` in these cases. In the future, once we only use C23, we can use the `[[maybe_unused]]` C23 attribute, see https://en.cppreference.com/w/c/language/attributes/maybe_unused
=> fix: fix unused variable error on non-Linux OSes

src/utils/iface.c, src/utils/iface.h, src/utils/nl.c, src/utils/uci_wrt.c, src/utils/uci_wrt.h
**Draft until #315 and #316 are merged**
This is because it relies on the new `list.h` function, as well as the new const `ipgen_` functions.
--
Makes the `iface_*` functions `const`, by making the following functions `const` too:
- `ipgen_*` Will be added by PR #316 
- `net_*` Added by PR #325
- `uci_wrt_*`
Fixes quite a few `-Wwrite-string` error in `recap.c` file.
=> Refactor `iface` functions so that they are `const`

.github/workflows/create-debs.yml
`ubuntu-latest` is in the process of migrating to using `ubuntu-22.04`. This means that it is effectively random whether our CI runner uses `ubuntu-20.04` or `ubuntu-22.04`, which is a problem, as due to a version mismatch in `ubuntu-20.04`'s default clang and default LLVM version, we currently manually specify clang v10.
`ubuntu-22.04` uses the same version for both clang and LLVM by default, so using that runner means we can remove our workaround. We should also get better error messages and more optimized code.
=> ci(build): use ubuntu-22.04 to run CI

src/dns/mcast.c
Declare the `ifr` variable only if it is truly required. Additionally, we also use `{}` scope to destroy the variable as soon as possible.
This fixes a FreeBSD compile error as well.
=> refactor(mcast): declare `ifr` only if required

lib/uthash.cmake, src/dhcp/dnsmasq.c, src/edgesec.c, src/utils/hashmap.c
Use commit https://github.com/troydhanson/uthash/commit/85bf75ab7189858f97b83a90a1426a1d5420d2d6
of uthash, which contains some bug fixes, such as removing the need for `strdup`.
Since we removed `_POSIX_C_SOURCE=200809L` from `uthash`, I had to set it manually on some files that still use POSIX extension functions.
=> Update uthash to commit 85bf75ab7189858f97b83a90a1426a1d5420d2d6 (2022-11-07 master)

src/CMakeLists.txt, src/dhcp/dnsmasq.c, src/sqlhook.c, tests/dhcp/test_dnsmasq.c
Debian builds compile with `-Wformat-security` enabled.
This PR enables this flag, and fixes those errors.
See <https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html> for docs.
This caught a potential truncation bug in `dnsmasq.c` and a potential buffer overflow in `sqlhook.c`
=> Fix `-Wformat-security` errors

.github/workflows/create-debs.yml
Updates the `actions/checkout` to version 3.
Version 3 uses Node.JS v16 instead of v12, but this is fine, since we run our code on the official GitHub Actions runners, which have both versions of Node.JS pre-installed.
I'm surprised dependabot didn't make a PR for this (maybe we don't have it enabled for GitHub Actions in this repo?)
=> ci(build): update `actions/checkout` to v3

src/utils/os.c
Check the return code for `chdir("/")` in the function `become_daemon().`
There's a bunch of error cases for `chdir`, which we should never run into, but it's worth checking anyway (plus sometimes the compiler throws a warning/error if you don't check the return code).
See https://man7.org/linux/man-pages/man2/fchdir.2.html#ERRORS
=> fix(os): check chdir return code in become_daemon

tests/CMakeLists.txt
Link time optimization (LTO) seems to be causing some issues when doing `-Wl,--wrap` (e.g. link-time mocking).
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88643 and https://sourceware.org/bugzilla/show_bug.cgi?id=24415 for the bug reports.
Fixes a ``undefined reference to `log_levels'`` when compiling `wrap_log_levels` in the debian build (which uses `-flto=auto`).
=> build(tests): disable LTO for tests

CMakeLists.txt
CMake does not recommend modifying `CMAKE_C_FLAGS` directly if we can help it. Instead, we should be using `add_compile_options()`.
This also means that we no longer overwrite `CMAKE_C_FLAGS`, which will mean that `edgesec` works better with other build systems (e.g. pdebuild).
Depends on #360 and #363 (since we no longer overwrite `CMAKE_C_FLAGS`, some of the debian build's C_FLAGS cause errors that need to be fixed).
=> build(cmake): use add_compile_options not C_FLAGS

CMakeLists.txt, CMakeModules/CMakeToolchains/DefineOpenWRTSDKToolchain.cmake
Load the `--host` parameter for autoconf from the `CMAKE_C_COMPILER_TARGET` value.
This is the variable that is recommended to be used, see https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_TARGET.html
As a backup, we still load from `CMAKE_LIBRARY_ARCHITECTURE` if `CMAKE_C_COMPILER_TARGET` is empty, as when cross-compiling a debian using debuild, `CMAKE_C_COMPILER_TARGET` is not set.
=> build: load `--host` from CMAKE_C_COMPILER_TARGET

lib/mnl.cmake, lib/sqlite.cmake, lib/uuid.cmake
Improves the flags passed to autotools (used by libuuid, libmnl, libsqlite) to get edgesec compiled using [cheribuild](https://github.com/CTSRD-CHERI/cheribuild).
To do this, we need to pass `CFLAGS` (C compiler flags) and `LDFLAGS` (linker flags).
Additionally, `util-linux` uses [`SOLIB_LDFLAGS`](https://github.com/util-linux/util-linux/blob/5099e004b486e7c4f7153abc9843f49c1593fe66/configure.ac#L2721-L2722) to control linking for libraries.
However, these flags are first passed through [`libtool`](https://www.gnu.org/software/libtool). This causes issues when linking for ARM Morello PureCap on CheriBSD using cheribuild, as `libtool` clobbers the `-target aarch64-unknown-freebsd13` parameter.
Instead, we need to prepend the `-target aarch64-unknown-freebsd13` with `-XCClinker`, as that …
=> Fix cross-compiling libs using autotools with cheribuild

CMakeLists.txt, CMakePresets.json, lib/cmocka.cmake
Building tests is now controlled by the `BUILD_TESTING` flag, which is provided by `CTest`.
This allows us to cross-compile tests, which is useful for `cheribuild`, which has a QEMU emulator for running tests. This is also the standard way of doing things in CMake, see this guide to modern CMake: https://cliutils.gitlab.io/modern-cmake/chapters/testing.html
=> build(test): allow cross-compiling tests

src/CMakeLists.txt, src/ap/ap_service.c, src/ap/ap_service.h, src/capture/CMakeLists.txt, src/capture/middlewares/header_middleware/dns_decoder.c, src/capture/middlewares/header_middleware/mdns_decoder.c, src/capture/middlewares/header_middleware/packet_decoder.c, src/capture/middlewares_list.c.in, src/radius/radius_server.c, src/radius/radius_server.h, src/radius/radius_service.c, src/radius/radius_service.h, src/runctl.c, src/utils/CMakeLists.txt
Compile with the `-Wpedandtic` flag in the edgesec `src/` directory.
`-Wpedandtic` checks for a lot more C errors that are often allowed by the GCC/Clang compilers, but are technically incorrect in ISO C.
However, it's worth enabling, as since we are compiling for CheriBSD, we want to follow standard C as much as possible.
We need to disable the `-Wpedandtic` flag when compiling `nl`, however. This is because `nl` includes `linux/netlink`, which includes some 0-length arrays, which are invalid in ISO C.
In ISO C < C23, using an empty initializer list is illegal.
Instead, we can just make a pointer that points to NULL.
In ISO C, doing pointer arthemtic with a `(void *)` pointer is
undefined. If we instead switch to a `(char *)`, it's all fine!
I've also used ptrdiff_t and size_t when …
=> Compile edgesec `src/` dir with `-Wpedantic` and fix errors

tests/dhcp/test_dhcp_service.c, tests/dns/test_mdns_service.c, tests/test_runctl.c
For some our tests, in order to create some fake values, we were casting integers to pointers, which Cheri LLVM does not like.
Instead, we can use `mock_ptr_type()` to return a pointer type directly.
See: https://api.cmocka.org/group__cmocka__mock.html#gac267dacf70a0f82aa1521b01a1c98238
=> test: fix casting ints to pointers

src/CMakeLists.txt
Enables two more compiler warnings in an attempt to find and fix issues in edgesec.
Unfortunately, (or fortunately), these warnings didn't find any issues in our code, but at least we've got them enabled now, so they won't be added in the future!
Warn/error if checking for equality between floats.
This is because with floating point numbers, `0.1 + 0.1 + 0.1 != 0.3` (try it in Node.JS)
Compile the edgesec src/ directory with `-Wnull-dereference`.
This warns if the compiler detects that you are attempting to
derefence NULL.
(otherwise, this is undefined behaviour, and the compiler may do some
crazy optimziations that breaks your program)
=> Compile with `-Wfloat-equal` and `-Wnull-dereference`

src/utils/allocs.c, src/utils/allocs.h
Instead of using our own implementation of calloc, we should use the C standard library version of [`calloc`](https://en.cppreference.com/w/c/memory/calloc).
This is because it will likely be faster, as instead of manually zero-ing memory in edgesec, the OS can just return pre-zeroed memory for us. See https://blogs.fau.de/hager/archives/825 for an example.
Additionally, by default, Linux uses overcommits memory using copy-on-write for memory allocation.
E.g., if you do `calloc(1, 2**40); // 1 GiB)`, Linux/MMU will allocate all 1 GiB of the memory to a single 4 KiB zero-ed page. Linux will then create a new memory page whenever you modify a page (so by default, `calloc(1, 2**40);` will use up 1 GiB of virtual RAM, and no physical RAM).
Physical RAM will only be used for any pages that you …
=> Optimize the `os_zalloc` and `os_calloc` functions by using `calloc`

src/CMakeLists.txt, src/utils/sockctl.c
Compile with `-Wstrict-prototypes` enabled.
This flag warns if creating a function in C without specifying params.
For example:
```c
// error: very dangerous, unspecified params
void my_function();
// correct! no params
void my_function(void);
```
=> Fix invalid function prototype

src/capture/capture_service.c
Using `=` should be at least as fast as memcpy, or even faster, when copying from one struct to another struct.
The main differences are:
1. assignment can ignore padding bytes
2. On CHERI architectures, when copying pointers, you must use load/store to keep capability metadata.
CHERI may do this automatically for `memcpy`, but there is a higher chance of success when using assignment, see https://github.com/CTSRD-CHERI/llvm-project/wiki/Unaligned-capability-copies
=> refactor(capture_service): use `=` not `memcpy`

src/utils/log.c, src/utils/log.h
Fix `-Wconversion` warnings in the log library.
This fixes a potential bug when `errno` was above 255.
For example, QNX uses 256 for `EISCONN`, which would currently overflow in our current code.
=> fix(log): fix `errno` overflow

lib/cmocka.cmake, tests/dhcp/test_dnsmasq.c
Use commit https://gitlab.com/aloisklink/cmocka/-/commit/55c444ee6ab77f27b188b09b1a32792d3a02d2f1 of CMocka, as it contains CheriBSD and Morello PureCap support.
The current list of important patches compared to CMocka v1.1.5 are:
- Adds Cheri Hybrid support https://gitlab.com/cmocka/cmocka/-/issues/38
- Support building with `C_EXTENSIONS` https://gitlab.com/cmocka/cmocka/-/merge_requests/51
- Work-around for FreeBSD libc bug https://gitlab.com/cmocka/cmocka/-/merge_requests/53
- CHERI PureCap fixes
- Use `__builtin_align_down` to align pointers https://gitlab.com/cmocka/cmocka/-/merge_requests/55
- Remove casts from `uintptr_t` to `uintmax_t` https://gitlab.com/cmocka/cmocka/-/merge_requests/56
=> Add CHERI PureCap support to CMocka library

lib/hostapd.cmake
Add a mirror for downloading the hostapd source code.
The official website for hostapd seems to be having some issues currently.
=> build(hostapd): add mirror URL for hostapd source code

.cirrus.yml
Cache the `build/dl` folder (aka the `EP_DOWNLOAD_DIR`), on Cirrus CI. This should speed up our CI, and prevent us from wasting open-source project's bandwidth.
See https://cirrus-ci.org/guide/writing-tasks/#cache-instruction
=> ci(cirrus): cache EP_DOWNLOAD_DIR folder

src/utils/os.c, src/utils/os.h, tests/utils/test_os.c
Implement `os_strlcpy` in terms of `memccpy()` and `strlen()`.
For most C libraries, `memccpy()` and `strlen()` are well optimized,
e.g. glibc uses AVX2 SIMD instructions, see https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/x86_64/multiarch/strlen-avx2.S;h=b9b58ef599c19d2b13f9ff27c8af4bfbffecb735;hb=f049f52dfeed8129c11ab1641a815705d09ff7e8
I did a quick test doing `os_strlcpy(buffer, "my test "string");` 1'000'000'000 times and the old implementation took ~20 seconds, the new implementation takes ~5 seconds (4x speedup).
This change also fixes the `-Wconversion` warning thrown by both GCC and Clang.
=> perf(os): improve performance of os_strlcpy (300% speed increase!)

src/utils/os.c, src/utils/os.h, tests/utils/test_os.c
Explicitly cast `int` to `uint8_t` to fix `-Wconversion` warning in the hexstr2bin() function.
I've also improved the types and fixed incorrect documentation for these functions.
=> refactor(os): supress -Wconversion hexstr2bin

src/utils/os.c
Implicitly cast `time_t` to `int_fast64_t` (should be a no-op on most 64-bit platforms), then explicitly cast the `int_fast64_t` to `unsigned int` to avoid `-Wconversion` error.
=> refactor(os): hide warning in os_init_random_seed

README.md
Improves the one-liner in the README.md that can be used to
- configure
- build
- test (if present)
- install (to `./tmp`)
Changes made:
- Add `--output-on-failure` to `ctest` command to print output on test failure.
- Move everything into one command.
- Fails the line if any of the subcommands fail. Currently, the `cmake --install` command still runs, even if the `ctest` command fails, which is a bit confusing since it hides the error messages.
---
Side-note @mereacre, I find this command really useful when doing `git rebase`, since you can do `git rebase --exec 'my_command_here'` and `git` will automatically run that command after every commit! https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---execltcmdgt
=> docs(README): improve one-liner for build/test

CMakePresets.json
Hide the FreeBSD ctest preset on Linux and other non-FreeBSD operating systems.
Although building for FreeBSD might make sense on Linux, (e.g. for cross-compiling), testing FreeBSD on Linux should never work, so it's safe to remove it.
Please only merge this PR once the FreeBSD tests pass.
=> build(cmake): hide FreeBSD ctest preset on Linux

.github/workflows/create-debs.yml
[GitHub Actions has deprecated the `set-output` command.][1]
They expect to disable the command fully in May 2023.
Migrating is pretty easy, all we need to do is replace the `echo "::set-output name={name}::{value}"` syntax with the new `echo "{name}={value}" >> $GITHUB_OUTPUT` syntax.
[1]: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
@AshleySetter, don't worry, despite being in the `edgesec` repo, this isn't C code :wink:
I'm guessing you also program in GitHub Actions' YAML DSL (YAML is an amazing programming language), so you might be interested in this change, if you haven't heard about it already.
=> ci: remove deprecated `set-output` commands

lib/cmocka.cmake
Use commit https://gitlab.com/cmocka/cmocka/-/commit/018bd67ad4791c8cdbfdc85b6191fced2a6f06c0 of CMocka, as the CheriBSD and Morello Purecap patches we need have now been upstreamed into the offical CMocka library. 🎉🎉🥳🥳
For a full list of what has changed, as well as the merge requests I submitted, please see commit https://github.com/nqminds/edgesec/commit/ed2b5f98d59523e29dd9864a0c7b25d66f95a7e6, which was submitted to EDGESec in https://github.com/nqminds/edgesec/pull/378
=> build(cmocka): use upstream cmocka

src/utils/os.c, tests/utils/test_os.c
Passing `signal_process(".", ...)` sends the signal to pretty much every running process, meaning pretty much everything on your computer gets killed.
This can occur, since under the [`basename` POSIX specification][1]:
> If string is a null string, it is unspecified whether the resulting
> string is '.' or a null string. In either case, skip steps 2 through 6.
Since we often call `signal_process(basename(some_str), ...`, this can often happen to us.
(guess how I found out 🤦)
This commit makes `signal_process(".", ` log and return an error. I've also added a test case for this scenario.
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/basename.html
=> fix(os): error signal_process() if passed "."

tests/ap/test_ap_service.c
The `generate_*_conf()` functions previously returned a `bool`, with `true` for success and `false` for failure.
However, 3196584bfea28817259dba98f4853609f5051f8a changed this behaviour, and made those functions use a return code, where `0` is success, and `-1` is for failures.
See:
https://github.com/nqminds/edgesec/blob/9854c1b57af0814fde321f12cd42a11e80192248/src/ap/hostapd.h#L25-L32 
https://github.com/nqminds/edgesec/blob/9854c1b57af0814fde321f12cd42a11e80192248/src/ap/hostapd.h#L34-L41
The C compiler didn't throw any issues, because the compiler doesn't check the signature for `__wrap_*` functions. Instead, it's only the linker that checks for these issues, and on most platforms, I believe returning a `bool` and `int` have the same ABI, since both use the same  register for return …
=> test(ap_service): fix return for generate_*_conf()

.github/workflows/create-debs.yml
~This may hopefully fix some of the `apt` issues we're having.~
Looks like the Ubuntu Apt issues have been fixed, but it's probably still worth merging this anyway.
=> ci(build-debs): run CI action on Ubuntu 22.04

.github/workflows/create-debs.yml, .github/workflows/pages.yml
GitHub Actions runs on Azure by default.
The Microsoft Azure apt mirror is constantly failing (see https://github.com/actions/runner-images/issues/7048), but we can setup a custom mirror file to automatically bypass the Azure apt server if it's failing.
We're essentially using the `mirrors.txt` file from http://mirrors.ubuntu.com/mirrors.txt (auto-generated based on location), but we append `http://azure.archive.ubuntu.com/ubuntu	priority:1\n` so that apt always tries the faster `http://azure.archive.ubuntu.com/ubuntu` mirror first, and only falls back to the other entries in `mirrors.txt` on failure.
See [*apt-transport-mirror(1)* man-page](https://manpages.ubuntu.com/manpages/jammy/en/man5/sources.list.5.html) for details.
The mirrors in `http://mirrors.ubuntu.com/mirrors.txt` are a lot …
=> Use apt `mirrors.txt` file to bypass apt server failures

CMakePresets.json
The `default` build preset no longer works, because you must enable one of the `USE_*_SERVICE` flags in order to compile `edgesec`.
We still use it for inheritance, however, so it's useful to keep. Hiding it means it won't show up in `cmake --list-presets`.
=> build(CMakePresets): hide `default` configure preset

lib/uci.cmake
Download `uci` (and `libubox`) as a tarball, instead of using a `git clone`.
Both `uci` and `libubox` are hosted on the [OpenWRT git server][1], which isn't very fast.
Downloading a tarball is quite a bit faster. Additionally, it means that we can easily store it in a custom `DOWNLOAD_DIR` and easily cache it, to prevent mutliple re-downloads.
Finally, doing `rm -r` on a git repo fails (you need `-f` to force delete it). Deleting an uncompressed tarball is much easier.
A few issues:
- In CMake v3.22.1, `;` is a list seperator character. Because GitWeb uses `;` in the URLs, we need to escape them in CMake using `\\\;` (double-escaped because CMake has some [interesting list unescaping issues][2]).
We also can't use [`$<SEMICOLON>`][3], because the URL parameter of `ExternalProject_Add()` …
=> build(uci): download uci archive, not `git`

lib/uuid.cmake
The current <https://codeload.github.com/karelzak/util-linux/tar.gz/refs/tags/v2.37.2> used to download util-linux seems to be broken on GitHub, it keeps on returning a 404 error.
Instead, we can use the official [`kernel.org` download page][1] to download util-linux.
The hashes for these files are signed by the maintainer of util-linux, and `.tar.xz` are also given, which are much smaller than `.tar.gz`.
[1]: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/
=> chore(deps): use kernel.org to download util-linux

src/utils/allocs.c, src/utils/allocs.h
Change `os_zalloc` to use `static inline` so that it uses internal linkage.
The libeap library also has it's own `os_zalloc`, which is causing linking errors. We can easily avoid this by inlining the edgesec version of `os_zalloc`. The function is literally just one-line of code, so inlining it should basically change nothing.
---
I made this commit to replace https://github.com/nqminds/edgesec/pull/380/commits/93d8c8a827c243cde9ffd4df20e5d6f1a77a02aa, since there's no need to rename `os_zalloc` to `sys_zalloc` if we can just inline the function.
=> refactor: inline os_zalloc for internal linkage

src/radius/common.h, src/utils/log.c, src/utils/log.h
Move the `printf_encode()` function into `radius/common.h` and inline it to avoid linking conflicts with the `printf_encode()` function in libeap.
---
This is the same commit as https://github.com/nqminds/edgesec/commit/c25c8fdccc7b98315affd664dc5fe7c77c1e976f, I just changed the description.
=> refactor: move printf_encode into radius/common.h

src/utils/os.c, src/utils/os.h
Inline the `hex2byte` function, and remove it from `src/utils/os.h`
We never call it outside of this file, but it may cause linking errors with libeap.
---
Adapted from https://github.com/nqminds/edgesec/commit/b273cce7c0e4a3fb234b655d2a49603b78db7e3a
The main difference is that instead of renaming the function, if we just inline it, this avoids linker issues (there were also some merge conflicts to fix).
=> refactor(os): inline hex2byte and remove from os.h

src/radius/wpabuf.c, src/utils/os.c, src/utils/os.h, tests/utils/test_os.c
Renames `hexstr2bin` to use the `edge_` prefix, so that it's called `edge_hexstr2bin`.
---
Adapted from https://github.com/nqminds/edgesec/commit/e53cebe3ffe81a39f184a7f2f4b54eba4e46ecd8
Differences:
- Instead of naming it `convert_hexstr2bin`, I've called if `edge_hexstr2bin`, since it makes more sense to have every function in edgesec share a common namespace prefix, and we've decided on `edge_` in https://github.com/nqminds/edgesec/pull/393#issuecomment-1406510314.
=> refactor(os): rename hexstr2bin with edge_ prefix

src/utils/os.c, src/utils/os.h
Rename `os_get_reltime` to `edge_os_get_reltime` to avoid linking conflicts with the `os_get_reltime` from libeap.
Use a `#define os_get_reltime edge_os_get_reltime` instead of renaming the function everywhere in our source code.
---
Adapted from https://github.com/nqminds/edgesec/commit/a873368103caf92e3351bf17a9117225f8965366, which renamed `os_get_reltime` to `get_reltime`, and didn't create a macro for `os_get_reltime`, so it had to be renamed in a bunch of places.
=> refactor(os): rename os_get_reltime with `edge_`

src/utils/os.c, src/utils/os.h
Rename `os_memcpy_const` to `edge_os_memcpy_const` to avoid linking conflicts with libeap.
I've also added a `#define os_memcmp_const edge_os_memcmp_const` macro, so we don't need to rename anything.
---
Adapted from https://github.com/nqminds/edgesec/commit/8268ac37b092cbd994afcdaf4f880d89b9cb05f5, which renamed `os_memcpy_const` to `sys_memcpy_const`, and didn't create a macro for `os_memcpy_const`, so it had to be renamed in a bunch of places.
=> refactor(os): rename os_memcpy_const with `edge_`

src/utils/os.c, src/utils/os.h
Rename `os_get_time` to `edge_os_get_time` to avoid linking conflits with libeap (it has it's own os_get_time too).
I've added a `#define os_get_time(t) edge_os_get_time(t)` macro so we don't need to change where we use it.
---
Adapted from https://github.com/nqminds/edgesec/commit/a082eff6ab7d131917dd980124b03637e79590e1, which renamed `os_get_time` to `sys_get_time`, and didn't create a macro for `os_get_time`, so it had to be renamed in a bunch of places.
=> refactor(os): rename os_get_time with edge_ prefix

src/utils/os.c, src/utils/os.h
Rename `os_get_random()` to `edge_os_get_random()` to avoid linking conflicts with libeap.
I've added a `#define os_get_random edge_os_get_random` macro so that we don't need to change references in the code.
---
Adapted from https://github.com/nqminds/edgesec/commit/d178bacc7469ddba0563182f214f564987b82727, which renamed `os_get_random` to `get_random`, and didn't create a macro for `os_get_random`, so it had to be renamed in a bunch of places.
=> refactor(os): rename os_get_random with `edge_`

.github/workflows/codeql-analysis.yml
Cache CMake's download dir when running the codeql-analysis GitHub Action.
All of the other CI actions cache this folder already, which makes the CodeQL-Analysis action a lot slower, for example:
https://github.com/nqminds/edgesec/blob/31398272b98ddc73d07c2e1f0de933e7fd99fcb5/.github/workflows/create-debs.yml#L52-L59
=> ci(codeql-analysis): cache CMake `build/dl` folder

src/radius/common.h, src/utils/allocs.c, src/utils/allocs.h
Change `os_memdup` to use `static inline` so that it uses internal linkage, to avoid conflicts with the `os_memdup` function defined in libeap.
I've also moved it from `src/utils/allocs` to `src/utils/common`.
---
Adapted from https://github.com/nqminds/edgesec/commit/e604195e077a58e5ac97a430310d54b2ae141b6c, except with a different commit message and fixed merge conflicts.
=> Move and inline `os_memdup` into `src/radius/common.h`

src/utils/net.c, src/utils/net.h
Rename `hwaddr_aton2` to `edge_hwaddr_aton2` to avoid potential linking errors with libeap.
I've added a `#define hwaddr_aton2(t) edge_hwaddr_aton2(t)` macro so we don't need to change where we use it.
---
Adapted from https://github.com/nqminds/edgesec/commit/5c5a32c3c891c5e269224a03656eae5abd2fe765, which renamed `hwaddr_aton2` to `convert_ascii2mac`.
Commit https://github.com/nqminds/edgesec/commit/17cf5d7772357233b5218b8c12315b6610feff0d also added curly-braces around the `while (*pos == ':' || *pos == '.' || *pos == '-')` loop in `hwaddr_aton2()`, so I extracted that into its own commit.
=> refactor(net): rename `hwaddr_aton2` with `edge_ `

src/radius/md5_internal.c, src/radius/md5_internal.h
Rename `md5_vector()` to `edge_md5_vector()` to avoid linking conflicts with libeap.
I've added a `#define md5_vector edge_md5_vector`, so that we don't need to change any usages of this function.
---
Adapted from https://github.com/nqminds/edgesec/commit/31bfdfd489ea6fb182509393fc35cb00e37f8ee0, which renamed `md5_vector` to `md5_vector_base`, and didn't create a macro for `md5_vector`, so it had to be renamed in a bunch of places.
(also, that commit has a bunch of other RADIUS junk in it).
=> refactor(md5_internal): rename `md5_vector` with `edge_` prefix

src/radius/md5.c, src/radius/md5.h
Rename/inline functions in `src/radius/md5.c` to avoid linker naming conflicts with libeap.
**[refactor(md5): rename `hmac_md5` with `edge_` prefix](https://github.com/nqminds/edgesec/commit/7d518e32354357512a621b967fe81c1be00924f4)** 
Rename `hmac_md5` to `edge_hmac_md5` to avoid a linker conflict when linking with libeap.
I've added a `#define hmac_md5 edge_hmac_md5`, so that we don't need to change any usage of this function.
**[refactor(md5): inline `hmac_md5_vector` in `md5.c`](https://github.com/nqminds/edgesec/commit/b470ebeacf3c7c81706734f34dbfd1f9cfbadefb)** 
We never use the `hmac_md5_vector()` function anywhere except in `md5.c`, so we might as well inline it. This also helps avoid linker conflicts when linking libeap, which also has a `hmac_md5_vector`.
---
Adapted from …
=> refactor(md5): avoid linker naming conflicts in `hmac_md5*` functions

src/utils/os.h
Source-code taken from the hostap project expects a `os_strncmp` call that points to [`strncmp`](https://en.cppreference.com/w/c/string/byte/strncmp).
---
Adapted from commit https://github.com/nqminds/edgesec/commits/12d15b2405aa6f2ab39a31d880499f8fc6f84c02, which instead names this macro `sys_strncmp`.
https://github.com/nqminds/edgesec/blob/12d15b2405aa6f2ab39a31d880499f8fc6f84c02/src/utils/os.h#L67-L69
Using `os_strncmp` is a lot easier, since then we can avoid changing any of the hostap code.
=> feat(os): add `os_strncmp` definition

src/utils/os.h
Source-code taken from the hostap project expects a `os_strstr` function/macro that points to `strstr`.
I've added a doc-string since [`strstr` is a type-generic function in C23][1], so it's has some unusual behaviour.
[1]: https://en.cppreference.com/w/c/string/byte/strstr
---
Adapted from commit https://github.com/nqminds/edgesec/commit/12d15b2405aa6f2ab39a31d880499f8fc6f84c02, which instead uses `sys_strstr`, and instead of macro, it just declares a function called `sys_strstr`, but never defines it anywhere:
https://github.com/nqminds/edgesec/blob/12d15b2405aa6f2ab39a31d880499f8fc6f84c02/src/utils/os.h#L88-L94
It also has a nice doc-string, but since [`strstr`][1] is a built-in ISO C function, it's probably not too important to have a doc-string (I think Doxygen should auto-link it to …
=> feat(os): add `os_strstr` definition

tests/utils/test_eloop_threaded.c
Test whether 1 million microseconds overflows to 1 second when running `edge_eloop_register_timeout()`.
This was causing code-coverage issues, because this path was occasionally not run in the current tests.
(source-code available at https://w1.fi/cgit/hostap/tree/src/utils/eloop.c?h=hostap_2_10#n791)
=> test(eloop): test if 1mil µs overflows to 1s

src/CMakeLists.txt, src/capture/middlewares/header_middleware/CMakeLists.txt, src/capture/middlewares/header_middleware/packet_decoder.h, src/edgesec-recap.c, src/radius/CMakeLists.txt, src/radius/common.h, src/radius/radius.h, src/utils/CMakeLists.txt, src/utils/attributes.h, src/utils/os.h, tests/CMakeLists.txt, tests/radius/CMakeLists.txt, tests/test_edgesec.c
For some reason, these lines are sometimes not run by tests, and because of that, we get a code-coverage warning:
https://github.com/nqminds/edgesec/blob/9b53dea608c87cb26cc5c25091f03f13afd8dfdc/tests/test_edgesec.c#L44-L45
I would have thought that these no-op statements are optimized out, even when compiling in debug mode, but I guess sometimes they are kept in?
To fix this, I've taken the `__maybe_unused` macro from PR #380 and stuck it in a new file called `src/utils/attributes.h`, which we can use for compiler attributes.
([C23 has built-in support for attributes](https://en.cppreference.com/w/c/language/attributes) like [`[[maybe_unused]]`](https://en.cppreference.com/w/c/language/attributes/maybe_unused), but since we're not using that, we're stuck with doing complicated …
=> Use `__maybe_unused` compiler attribute to fix flakey code-coverage in `test_edgesec`

src/utils/attributes.h
Use the [`__has_attribute`][1] macro to check for compiler support for `__attribute__((packed))`, so that `STRUCT_PACKED` also works on the Clang compiler.
(`__has_attribute` is supported by GCC, Clang, IBM compiler, and even the Oracle® Solaris Studio C compiler).
[1]: https://clang.llvm.org/docs/LanguageExtensions.html#has-attribute
=> refactor(attributes): fix `STRUCT_PACKED` in clang

src/utils/os.h
Source-code taken from the hostap project expects a `os_snprintf` function/macro that points to the ISO C99 `snprintf`.
---
Adapted from commit https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8.
I've instead given it some arguments to make it clear that it's a function.
=> feat(os): add `os_snprintf` definition

src/radius/common.h
Add `os_snprintf_error()` function from commit [0047306bc9ab7d46e8cc22ff9a3e876c47626473][1] from the hostap project.
It is used by source-code taken from hostap.
(side-note, we should probably be using it in our own code too!)
[1]: https://w1.fi/cgit/hostap/commit/?id=0047306bc9ab7d46e8cc22ff9a3e876c47626473
---
Adapted from commit https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8.
I've also given the function a doc-string, and documented where the function came from.
=> feat(common): add `os_snprintf_error()`

src/utils/CMakeLists.txt, src/utils/allocs.h, src/utils/attributes.h
Add a `__must_check` attribute to that tells Clang/GCC that the return code for a function must be used.
This attribute may be used by code taken from the `hostap` project.
The original implementation from `hostap` was GCC specific, so I modified it to work with Clang as well.
---
Adapted from commit https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8, although that was in `src/utils/common.h` and only worked for GCC, not Clang.
---
Since we've added it, I've also set `__must_check` on a bunch of functions that returns a pointer that must be free-d, such as:
- `os_zalloc`
- `os_memdup`
- `os_realloc_array`
- `os_strdup`
The return values of all these functions must be `free()`-ed, so it's a bug if we don't check their return codes.
=> refactor(allocs): add `__must_check` compiler attribute

src/radius/common.h, src/utils/log.c, src/utils/log.h
Instead of using an `int` that is either `0` or `1` for the param `uppercase` in the function `printf_hex()`, we can instead use an ISO C99 `bool` that is `true` or `false`.
---
While I was at it, I also documented what the `printf_hex` function does, because the return code is a bit intuitive.
I've also documented that the code is taken from hostap at https://w1.fi/cgit/hostap/tree/src/utils/common.c?h=hostap_2_10#n317 and is covered by the `BSD-3-Clause` license.
=> refactor(log): use C99 bool as `printf_hex` param

src/radius/common.h
Add `wpa_hexdump_ascii` to match the API of `wpa_hexdump_ascii()` from hostap.
Please note that this function acts differently from the hostap version of the function:
- It only prints the first 16 bytes.
- It prints all bytes as hex, never as ASCII.
---
Adapted from commit https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8.
My changes compared to https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8:
- Added documentation
- Use `__maybe_unused` (from https://github.com/nqminds/edgesec/commit/5a3a8bf22e4976c8fe9ff37daa1e221fd299da01) to mark the unused `level` param.
- I've changed the number of bytes in the buffer to 33 instead of 32. This is because we need a byte for the `NUL`-terminator too (see …
=> feat(common): add wpa_hexdump_ascii function

src/radius/common.h
Document dummy `wpa_trace_show()` function for code taken from hostap.
In the hostap source-code, this function is supposed to print a backtrace to help debugging (see https://w1.fi/cgit/hostap/tree/src/utils/trace.h?h=hostap_2_10#n33), but we don't have backtrace tools in edgesec
In the future, we could use something like GCC's [backtrace_symbols()](https://www.gnu.org/software/libc/manual/html_node/Backtraces.html) to easily implement this.
=> doc(common): document `wpa_trace_show` definition

src/radius/common.h
The `TEST_FAIL()` macro is used in hostap's source-code to test handling failing functions, see [commit 2da525651d9aa49854bff51f7e4faf9273f68868 of hostap][1]
It can be set to `0` to be ignored in production code.
[1]: https://w1.fi/cgit/hostap/commit/?id=2da525651d9aa49854bff51f7e4faf9273f68868
=> doc(common): document `TEST_FAIL()` definition

src/radius/md5_internal.c, src/radius/md5_internal.h
Remove the following functions from `md5_internal.h` and give them internal linkage by marking them as `static`:
- `MD5Init`
- `MD5Update`
- `MD5Final`
These functions are never called outside of `md5_internal.c`, and they cause linker conflicts with libeap.
---
Adapted from https://github.com/nqminds/edgesec/commit/14b490ebdab06078acea0b3c41afd3b689b4cc51.
In that commit, all the functions were renamed to `MD5Init_base`, `MD5Update_base`, `MD5Final_base`, but again, we never call them outside of `md5_internal.c` so there's no need to rename them.
=> Remove external linkage from some `md5_internal.c` functions

src/utils/os.h
Source-code taken from the hostap project expect a `os_strcmp` call that points to [`strcmp`][1].
[1]: https://en.cppreference.com/w/c/string/byte/strcmp
---
Adapted from commit https://github.com/nqminds/edgesec/commit/208bd48fab403ef2fc736aefcdcc90b14a6a3960 except I've kept the same `os_strcmp` name as in the hostap source-code, so that we can change less code.
We don't need to worry about linker conflicts, because it's only a pre-processor macro, not a function.
=> feat(os): add `os_strcmp` definition

src/radius/common.h
The `#include` statements for `allocs.h` and `log.h` was using the directory included directly by CMake in the compiler flags.
---
Adapted from changes in https://github.com/nqminds/edgesec/commit/2704b75351c6f688450766efd33a2ccd67fa1ff1.
---
I'll be honest, I'm not actually sure how the C compiler is finding these files, maybe it is being caused by, but I'm pretty sure that should only affect code in the `tests/ap` folder:
https://github.com/nqminds/edgesec/blob/51b815f7cc16539a486c8b1f61c9f357b7010f59/tests/ap/CMakeLists.txt#L1-L3
=> refactor(common): fix relative `#includes`

src/radius/CMakeLists.txt
Make a CMake `INTERFACE` library for `radius_config`, so that we can properly track dependencies on `net` and `os`.
=> build(radius_config): make radius_config CMake lib

src/radius/CMakeLists.txt, src/radius/radius_config.h, src/radius/radius_server.h, src/radius/radius_service.h
> **Warning** This PR is based on the follow PRs. Please merge those PRs first before reviewing this PR.
>   - #447
Add the `typedef` for `mac_conn_fn` (aka the RADIUS service callback function type) into `radius_config.h` from `raidus_server.h`.
---
Adapted from https://github.com/nqminds/edgesec/commit/2704b75351c6f688450766efd33a2ccd67fa1ff1#diff-b7d28264f51b9a714c5a677956b5d87cbb993f1882bc1cf2543309b11bd55b97R32.
I'm guessing you wanted to keep `src/radius/radius_server.h` as untouched as possible, to make it easier to pull in changes from newer versions of hostapd?
=> refactor: move `mac_conn_fn` type to `radius_config`

src/utils/os.h
> **Warning** This PR is based on the follow PRs. Please merge those PRs first before reviewing this PR.
>   - #444
Source-code taken from the hostap project expects a `os_strchr` function/macro that points to `strchr`.
I've added a doc-string since [`strchr` is a type-generic function in C23][1], so it's has some unusual behaviour.
[1]: https://en.cppreference.com/w/c/string/byte/strchr
---
Adapted from commit https://github.com/nqminds/edgesec/commit/208bd48fab403ef2fc736aefcdcc90b14a6a3960 except I've kept the same `os_strchr` name as in the hostap source-code, so that we can change less code.
We don't need to worry about linker conflicts, because it's only a pre-processor macro, not a function.
=> feat(os): add os_strchr definition

src/radius/common.h
Add `bin_clear_free()`, which is used to set memory to `'\0'` before `free()`-ing it, to avoid leaking sensitive information.
Required by code taken from `hostap`.
Unfortunately, the `memset()` might still be optimized out by a smart compiler. C11 has `memset_s`, but it's part of Annex K, which means basically nobody except Microsoft supports it, so there's not much point if us trying to use it.
C23 has `memset_explicit`, but C23 is not out yet, so we can't use it.
Alternatively, we could use the non-standard [`explicit_bzero`][1] function. It's available in glibc, and most BSDs. But, we'd probably then need to:
- a) add CMake code to call [`check_symbol_exists`][2]
- b) add it to a `.c` file, not a `.h` file, to set the appropriate glibc flags.
[1]: …
=> feat(common): add `bin_clear_free` function

src/ap/CMakeLists.txt, src/ap/hostapd.h, src/radius/CMakeLists.txt
> **Warning** This PR is based on the follow PRs. Please merge those PRs first before reviewing this PR.
>   - #447
Add an `#include "../radius/radius_config.h"` to `hostapd.h`.
This file uses the `struct radius_conf` type since https://github.com/nqminds/edgesec/commit/ef7e8a8bf82e05dbe6c97ddb23b27ab86f385950, which is defined in `../radius/radius_config.h`, so we should include that file directly.
---
This was changed in https://github.com/nqminds/edgesec/commit/a57300acc8bbef74d78aa3b24dd92addbbfb023c#diff-a0c8ed555c1e224c6ec46a0265e118f7d0b7ffe6bfe2aae2af7ad57123616feaR21, but I'm not 100% sure why.
I think @mereacre did it because there's `struct radius_conf` in this file, so that's what I've stuck in this PR/commit description (if I'm wrong, let me know @mereacre).
=> refactor(hostapd): include `radius_config`

src/supervisor/CMakeLists.txt, src/supervisor/supervisor_config.h
> **Warning** This PR is based on the follow PRs. Please merge those PRs first before reviewing this PR.
>   - #447
Add an `#include "../radius/radius_config.h"` to `supervisor_config.h`.
This file uses the `struct radius_conf` type since https://github.com/nqminds/edgesec/commit/24c49d59fa36b3fc8e97a24a0b0a199fdae18bf1, which is defined in `../radius/radius_config.h`, so we should include that file directly.
---
This was changed in https://github.com/nqminds/edgesec/commit/2704b75351c6f688450766efd33a2ccd67fa1ff1#diff-c92e4b6dccbcdfb60672a8b00773227eddcc9c4ba6ee87a3ac46dcef04b41b4cR19, but I'm not 100% sure why.
I think @mereacre did it because there's `struct radius_conf` in this file, so that's what I've stuck in this PR/commit description (if I'm wrong, let me know @mereacre).
=> refactor(supervisor_config): include `radius_config`

tests/CMakeLists.txt, tests/test_edgesec.c
Improves `test_edgesec.c` by making the following changes:
- [**test(edgesec): use `threads.h` in test_edgesec**](https://github.com/nqminds/edgesec/commit/a8d1aa93e6fbd86a662c67cc432a857f8ea7f27c) 
Use `#include <threads.h>` (aka ISO C11 standard threads) instead of `#include <pthreads.h>` in `test_edgesec.c`
Using C11 standard threads caught a double-free error, so it's already
better!
- [**test(edgesec): stop eloop threads gracefully**](https://github.com/nqminds/edgesec/commit/d76a2787da075bbc33d1177fe9336bf99ddbb82b)
Currently, the eloop threads are never actually stopped. We call `edge_eloop_terminate()`, but this is not thread-safe.
To fix this, we can use a threadsafe atomic from `<stdatomic.h>`, which is constantly checked by eloop, which then automatically closes the eloop when …
=> Improves `test_edgesec.c`

src/utils/os.c
The `kill_dir_fn()` is not used anywhere in edgesec. The more generic `signal_dir_fn()` fully replaced it in f25fcb6e, so we might as well remove it.
See:
https://github.com/nqminds/edgesec/blob/c0122002fc6e8fb007f8f1cdaedd2509d2baa0e2/src/utils/os.c#L854-L875
=> refactor(os): remove unused `kill_dir_fn()`

src/utils/os.c
Add a check to avoid calling `strlen(NULL)` when `valid_right` is `NULL`.
=> fix(os): handle NULL valid_right in construct_path

src/utils/os.c, src/utils/os.h
This function was only used in the old `restsrv.c` code, which was removed from edgesec in commit e4931bcf404b14a4ec23f80932dcdc8bd57ae6fa.
The last time this function was used:
https://github.com/nqminds/edgesec/blob/cbcdc8237f199208afe40278e2e7512241d60546/src/restsrv.c#L253
=> refactor(os): remove unused `upper_string()` func

src/utils/os.c
Currently, if `fread()` has an error in `read_file()`, `fp` is closed twice, and there is no error return code. Adding a `return -1;` fixes this.
=> fix(os): fix fread error handling in read_file()

src/utils/os.c, src/utils/os.h
The following branch of `read_file_string()` in `src/utils/os.c` causes a memory leak, because it is missing an `free(data);`
https://github.com/nqminds/edgesec/blob/c83625b9d320cc8db6140181d5108706da48a6ad/src/utils/os.c#L1428-L1431
I've also stuck `free(data)` in the branch for https://github.com/nqminds/edgesec/blob/c83625b9d320cc8db6140181d5108706da48a6ad/src/utils/os.c#L1423-L1426, since data is NULL anyway if `read_file()` has an error, and `free(NULL)` is perfectly safe.
---
One think I also noticed, is that in the following lines of code, we could replace everything with a [`realloc()`](https://en.cppreference.com/w/c/memory/realloc), see https://github.com/nqminds/edgesec/commit/371584fda8b7db611c27556e09c689c787d8f4c6:
https://github.com/nqminds/edgesec/blob/c83625b9d320cc8db6140 …
=> Fix a potential memory leak in `read_file_string()`

src/utils/os.c
The `path` in `get_secure_path()` might be `NULL` if `construct_path()` fails due to a memory allocation error.
=> fix(os): handle NULL path in `get_secure_path()`

src/utils/os.c, src/utils/os.h, tests/ap/CMakeLists.txt, tests/ap/test_hostapd.c
`is_proc_app()` currently returns the `pid_t` if the proc_name is the PID's `/proc/[pid]/exe`'s basename, OR if the proc_name is anywhere in the `/proc/[pid]/cmdline`.
This is far far far too broad.
For example, if I run the following:
```bash
/usr/bin/bash -c 'echo "Modifying /etc/hostapd.conf"; sed ...'
```
`is_proc_app(pid_dir, "hostapd")` will return that PID, because `hostapd` is in the argv2 string!
This also causes a bunch of false positives. For example, `signal_process("dnsmasq", SIGHUP);` kills `test_dnsmasq`, and so prevents tests from being run in parallel (fixes https://github.com/nqminds/edgesec/issues/425).
And `is_proc_running("hostapd")` returns `true` for `test_hostapd`.
Instead, it makes a lot more sense only to check the basename of the argv0 string.
For example, when …
=> Makes `is_proc_app()` stricter, so that it only looks at the process name

tests/utils/test_os.c
Add some basic tests that ensure that the `is_proc_app()` and `is_proc_running()` functions work, as since https://github.com/nqminds/edgesec/commit/98ad7c655807b63f47dc32b1d4925a9c7b74e7f1, there are no longer tested.
Because `/proc/[pid]` is Linux specific, I'm only running these tests `#if __linux__`.
(FreeBSD used to have it in the old days, and still has [linprocfs](https://man.freebsd.org/cgi/man.cgi?query=linprocfs&apropos=0&sektion=5&manpath=FreeBSD+13.0-RELEASE&arch=default&format=html), but it's not enabled by default)
https://github.com/nqminds/edgesec/blob/f7179087fd54479b656b51d32b597fc0812b45c2/src/utils/os.h#L445-L462
https://github.com/nqminds/edgesec/blob/f7179087fd54479b656b51d32b597fc0812b45c2/src/utils/os.h#L496-L502
=> Test `is_proc_app()` and `is_proc_running()`

src/radius/common.h
Adds an enum for all of the log levels that code taken from hostap expects (e.g. like `MSG_INFO`).
---
Adapted from https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8, but I've changed the `enum` to be named instead of anonymous.
This means that we can specific that the type of `level` param to `wpa_hexdump_ascii()` is `enum hostap_log_level`, which is more specific than just `int`.
=> feat(common): add `enum hostap_log_level` enum

src/utils/allocs.h, src/utils/attributes.h
Add the `__must_free` attribute, that in GCC 11 or later, is defined as:
`#define __must_free __attribute__((malloc(free, 1)))`.
Basically, it tells GCC that the result of these functions must:
1. be checked for `NULL`
2. must be deallocated by `free()`
Otherwise, when compiling code that uses these functions in GCC with the `-fanalyzer` option, you'll get a warning that looks a bit like this:
```
<source>:17:1: warning: leak of 'x' [CWE-401] [-Wanalyzer-malloc-leak]
'my_func': events 1-2
|
|   15 |   char * x = my_malloc(sizeof(int));
|      |              ^~~~~~~~~~~~~~~~~~~~~~
|      |              |
|      |              (1) allocated here
|   16 |   printf("%p", x);
|   17 | }
|      | ~             
|      | |
|      | (2) 'x' leaks here; was allocated at (1)
|
Compiler returned: 0 …
```
=> Add a new GCC attribute called `__must_free` to warn if pointers aren't deallocated

src/utils/os.c
Fix a potential NULL dereference error in `list_dir()` in `src/utils/os.c`, if the call to `construct_path()` returns `NULL` due to a memory allocation error.
https://github.com/nqminds/edgesec/blob/8dc7acb0364487c925df4e4566ef7cabe6f72b79/src/utils/os.h#L410-L418
=> fix(os): fix NULL deref in `list_dir()`

src/radius/common.h
Match the log levels used by source-code taken from hostap with the log levels used by edgesec, instead of always just using `LOGC_TRACE`.
This means that messages from the radius server will now be logged by default, and they'll be colour-coded for severity.
@mereacre, I don't know how verbose the `radius_server` is. If it's too much logging compared to the rest of edgesec, you're welcome to push down the values of `enum hostap_log_level`, e.g. so that `MSG_ERROR` only equals to an edgesec `LOGC_WARN`, for instance.
=> refactor(common): match wpa log levels to edgesec

src/radius/common.h, src/radius/radius_server.h
Move `struct hostapd_radius_attr` from `src/radius/radius_server.h` to `src/radius/common.h`.
I'm guessing this is to keep `src/radius/radius_server.h` as close to the upstream `hostapd` source-code as possible.
It's used by the hostapd source-code to store RADIUS attributes.
See
https://w1.fi/cgit/hostap/commit/?id=af35e7af7f8bb1ca9f0905b4074fb56a264aa12b
---
Adapted from https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8. I've instead used `uint8_t` instead of `u8`, to match standard ISO C types, and added documentation.
=> refactor: move `hostapd_radius_attr` into common

README.md
`ctest` previously had some race conditions that caused intermittent failures when running in high job counts (e.g. `ctest -j16`) (see issue https://github.com/nqminds/edgesec/issues/425)
However, since commit https://github.com/nqminds/edgesec/commit/a7e09d0a120cf6c7b227275fa1e842738d940b0f, this has now been fixed and `ctest -j16` works fine!
This speeds up tests by a few seconds!
=> docs(README): test in parallel

src/radius/common.h
Define `WLAN_REASON_IEEE_802_1X_AUTH_FAILED`, used by hostapd source-code, see https://w1.fi/cgit/hostap/tree/src/common/ieee802_11_defs.h?h=hostap_2_10#n213
---
Adapted from commit https://github.com/nqminds/edgesec/commit/dff384c0c21e41af7da63a45bfb3574322a6f9c8, except I've changed it to an `enum` instead of a `#define` since it's a bit cleaner that way (and I've added documentation).
=> feat(common): define WLAN_REASON_IEEE_802_1X_AUTH_FAILED

tests/test_edgesec.c
Currently, only the OpenWRT test presets of edgesec sends an "ATTACH" command to the AP server, which is compiled with GCC.
This causes an issue with code-coverage, because this means that this branch is only covered by code compiled/tested with GCC, and not via LLVM/Clang. Testing this branch in Clang should hopefully fix this code-coverage issue.
Should hopefully fix https://github.com/nqminds/edgesec/issues/435.
=> test(edgesec): test "ATTACH" to ap server

src/utils/os.c
The GCC static analyzer thinks that we're calling `strlen(NULL)`, so we should simplify the code so it knows that we never call it.
I've also replaced a call to `os_zalloc()` with a call to `os_malloc()`, and I'm just manually setting the first char to NUL to make a NUL-terminated string, which should be slightly more efficient.
=> refactor(os): simplify `concat_paths()`

src/supervisor/cmd_processor.c, src/supervisor/cmd_processor.h
Handle `ENOMEM` errors in `process_get_all_cmd()`.
Previously, this function wasn't checking whether `os_zalloc` or `os_realloc` was working correctly.
**Changes**:
I've changed the function so that if `mac_list_len` is `0`, `write_socket_data(sock, "", strlen("")...)` will now be called instead of `write_socket_data(sock, NULL, strlen(NULL)...)`. This seems better to me, since previously, calling `strlen(NULL)` would have been undefined behaviour.
=> fix(cmd_processor): handle ENOMEM in `process_get_all_cmd()`

src/utils/CMakeLists.txt, src/utils/attributes.h, src/utils/squeue.c, src/utils/squeue.h, tests/utils/test_squeue.c
Handle ENOMEM errors when `realloc()`-ing memory in `concat_string_queue()` properly to avoid memory leaks.
=> Handle `ENOMEM` in `concat_string_queue()`

src/supervisor/cmd_processor.c
Refactors and tidies up the source-code for the `process_get_bridges_cmd()` by declaring variables only when they are used (supported since C99).
In this PR, I've also added the following changes (it may be easier to review this PR commit by commit):
- Change the `process_get_bridges_cmd()` function to return early,
so that we can un-indent most of the function code, and move it out of the `if-` scope, see
[**refactor(cmd_processor): return early in `process_get_bridges_cmd()`**](https://github.com/nqminds/edgesec/commit/8dfb3f23f2bcec42806cad0ff11e1238b76a13ea)
- Replace the `while()`-loop with a `for()`-loop to iterate over the utarray, as shown in the examples in https://troydhanson.github.io/uthash/utarray.html, see [**refactor(cmd_processor): use `for`-loop, not …
=> Tidy up `process_get_bridges_cmd()` using C99 syntax

src/supervisor/cmd_processor.c, src/supervisor/cmd_processor.h, src/supervisor/subscriber_events.c, src/supervisor/subscriber_events.h, src/supervisor/system_commands.c, src/supervisor/system_commands.h
Make the `client_addr` parameter in `cmd_processor` `const`, as we only ever read the value and never change anything.
Even when we call `utarray_push_back(..., addr)`, utarray by default does a `memcpy` to insert the new data, so it also doesn't modify the original pointer, see <https://troydhanson.github.io/uthash/utarray.html#_about_ut_icd>.
=> Make the `client_addr` parameter in `cmd_processor` `const`

src/supervisor/cmd_processor.c, src/supervisor/cmd_processor.h
Make the `cmd` parameter of `get_command_function()` `const`.
We only read this string and never change it, so we might as well make it `const`.
---
Side-note, all the `strcmp(...)` are a bit slow, since it's $O(n)$ (i.e. it scales linearly with the number of command types.
We could switch to using a hashmap (like [uthash.h](https://troydhanson.github.io/uthash/userguide.html)), which would be $O(1)$ (i.e. constant time with every command type), but if we only have 25 message types, I've got no idea how big the speedup will be :shrug:
Still, it's something to consider the more message types we add.
=> Make the `cmd` parameter in `get_command_function() `const`

src/utils/uci_wrt.c
Simplifies the `uci_lookup_section_ref()` function.
- Removes a `malloc()` call that we don't need (since `malloc(x)` is equivalent to `realloc(NULL, x)` (046570f6dc2d1d2dbe36d27cdee61083b1ba48f7)
- Removes an unnecessary `NULL` check (we've already checked for memory allocation failures earlier in the function)  (6576dfdbea68137a5300e5cb6f89a53803082854)
- Makes the `uci_lookup_section_ref()` function `static`, since we never use it outside of `uci_wrt.c` (5eb29b821b567ea6371245f06e31aa589a84ab64)
- Declare variables as close as possible to where the variables are actually used, since that's supported in C99 (1b93f254730c7c9e4bfa656f24b3328be163ede9)
---
There's a bunch of extra stuff I haven't changed, since I don't actually understand what this function does. Also, it looks like the …
=> Simplify `uci_lookup_section_ref()` function

src/edgesec-recap.c
Free the memory of `pctx.pcap_data` when edgesec-recap closes.
This isn't too big of a deal, since on pretty much every OS that we care about, the OS will automatically free this leaked memory when edgesec-recap exits. Still, it's worth explicitly `free()`-ing this memory, otherwise static analyzers, or [Valgrind](https://valgrind.org/) will print a bunch of warnings.
=> Fix `pctx.pcap_data` memory leak in `edgesec-recap`

src/edgesec-recap.c
Currently, if `os_realloc()` in `read_pcap()` fails due to an `ENOMEM` error, there will be a memory leak, since we lose the original pointer. This is because the anti-pattern `PTR = realloc (PTR, sz)` leaks memory on failure.
Instead, we need to do:
```c
void *NEW_PTR = realloc (PTR, sz);
if (NEW_PTR == NULL) {
// handle error
} else {
PTR = NEW_PTR;
}
```
=> Handle `ENOMEM` in `read_pcap()` in the `edgesec-recap` binary

src/utils/uci_wrt.c
Fix the `uwrt_lookup_package()` function in `uci_wrt.c`.
`uwrt_lookup_package()` is currently never adding anything to it's `list` param, which means that the count for anonymous section references is always 0. (this is also the cause of the memory leak in #481).
For example, given the following UCI file:
```conf
config rule
option hi 'hi'
config rule
option hi 'hi'
config rule
option hi 'hi2'
```
Output:
| # | Current | Expected |
| -: | -- | -- |
|  0 | `@rule[0]` | `@rule[0]` |
|  1 | `@rule[0]` | `@rule[1]` |
|  2 | `@rule[0]` | `@rule[2]` |
To fix this, I've instead changed `uci_lookup_section_ref()` to use a [uthash.h](https://troydhanson.github.io/uthash/userguide.html) hashmap as a counter, instead of a custom linked-list.
Fixes #481
For the following functions, I've also made …
=> Fix `uwrt_lookup_package()` in `uci_wrt.c`

tests/utils/test_log_thread_safe.c
Make the format-string in `log_trace()` in the `test_log_thread_safe` a string literal to avoid format string injection attacks/bugs (see <https://en.m.wikipedia.org/wiki/Uncontrolled_format_string>).
=> Make format string in `log_trace` a literal to avoid format string injection attacks/bugs

src/supervisor/sqlite_macconn_writer.c
Fix the error that is printed when `make_dirs_to_path()` fails in `open_sqlite_macconn_db()`. Currently, the wrong variable is printed, as it should be the path that is printed, not a NULL pointer.
=> Fix `make_dirs_to_path()` error message

src/radius/wpabuf.c
GCC throws an warning when trying to pass a non-`void *` pointer to a `%p` in a format string. This might be a bug in GCC, since I'm pretty sure this is explicitly valid behaviour in C.
Manually casting the pointer to `(const void *)` seems to fix this warning from GCC.
=> Cast `%p` format argument to `(void *)` to silence GCC warning

src/radius/common.h, src/utils/os.c, tests/ap/test_ap_service_failure.c
Use `"%zu"` to format/log `size_t` values.
`z` is the correct length modifier for an integer of size `size_t`.
This doesn't make much of a difference on 64-bit OSes, but it does cause issues when we cross-compile for 32-bit platforms like OpenWRT.
> 
> Taken from the [format specifiers table on cppreference.com](https://en.cppreference.com/w/c/io/fprintf), used under [CC-BY-SA 3.0](https://en.cppreference.com/w/Cppreference:Copyright/CC-BY-SA)
=> Use `%zu` to format `size_t` values

src/radius/radius_server.c, src/utils/sockctl.c, src/utils/squeue.c, tests/dhcp/test_dnsmasq.c, tests/utils/test_eloop_threaded.c
Use `"%zd"` to format and/or log `ssize_t` (signed `size_t`) values. `z` is the correct length modifier for an integer of size `size_t`.
This doesn't make much of a difference on 64-bit OSes, but it does cause issues when we cross-compile for 32-bit platforms like OpenWRT.
> 
> Taken from the [format specifiers table on cppreference.com](https://en.cppreference.com/w/c/io/fprintf), used under [CC-BY-SA 3.0](https://en.cppreference.com/w/Cppreference:Copyright/CC-BY-SA)
=> Use `%zd` to format `ssize_t` values

src/utils/sockctl.c
Fix the error message when `unlink()` fails to cleanup the temporary domain socket in `cleanup_tmp_domain_socket_path()`.
We should be using `"%s"` to log a string.
=> Fix `unlink()` error message in `cleanup_tmp_domain_socket_path()`

src/utils/cryptou.c
Fix a potential overflow error when logging the error code from OpenSSL's [`ERR_get_error()`][1] function.
This value is an `unsigned long` (`"%lu"`), not an `int` (`"%d"`).
In the future, we should probably replace these error messages with the more human-readable [`ERR_error_string()`][2] function.
[1]: https://www.openssl.org/docs/man3.1/man3/ERR_get_error.html
[2]: https://www.openssl.org/docs/man3.1/man3/ERR_error_string.html
=> Fix overflow error when logging `ERR_get_error()` (OpenSSL error)

src/edgesec-recap.c
Currently, `process_file_stream_state()` formats a `uint64_t` using `%zu`. This is valid on 64-bit machines, but on 32-bit machines, this value is too small. Instead, `PRIu64` should be used.
`PRIu64` is declared in the [Format macros constants section of standard ISO C`<inttypes.h>`](https://en.cppreference.com/w/c/types/integer).
=> Fix logging on 32-bit machines in `edgesec-recap` executable

tests/utils/test_eloop_threaded.c
According to the POSIX standard, `in_port_t` should always be equivalent to `uint16_t`, see [IEEE Std 1003.1, 2004 (aka POSIX.1-2004), `netinet/in.h`][1].
`PRIu16` is the format macro constant for `uint16_t`, defined in [`<stdint.h>`](stdint.h)
[1]: https://pubs.opengroup.org/onlinepubs/000095399/basedefs/netinet/in.h.html
=> test(eloop): use `PRIu16` to log `in_port_t`

tests/test_edgesec.c
Currently, `check_if_should_terminate()` runs 10ms after being registered for the first time.
In rare-cases, this is long enough that all the test-code is already done, and therefore `check_if_should_terminate()` quits the thread without ever registering another `check_if_should_terminate()` timeout.
This causes issues with code-coverage, as it means that the following branch sometimes never runs:
https://github.com/nqminds/edgesec/blob/e0acb2cacc426fc2993f0fa314e1c3a3f1a4ea16/tests/test_edgesec.c#L269-L270
See the below code-coverage result:
> ![image](https://user-images.githubusercontent.com/19716675/223388578-f1dc9c55-a6ce-40c2-b8c4-5a6bc3e2790a.png)
> 
> Code-coverage result, screenshot taken from https://app.codecov.io/gh/nqminds/edgesec/pull/493/blob/tests/test_edgesec.c#L270.
> …
=> Run `check_if_should_terminate()` immediately to avoid race-conditions in code-coverage

src/supervisor/cmd_processor.c
We're using `%s` to format an `int`, which is incorrect.
Fixes: b04ad88be46b67a335fd2f78ad34eec6e75a373f
---
Yep, I made this bug yesterday in PR https://github.com/nqminds/edgesec/pull/477 :facepalm:
In my defence, the `s` and `d` keys on my keyboard are quite close together.
=> Fix incorrect format specifier for an `int` in `process_get_bridges_cmd()`

src/radius/radius_server.c
Currently, we're using `"%ld"` to log an `int` value instead of the correct `"%d"` format specifier.
On 64-bit OSes, this makes no difference, but on 32-bit OSes, `long int` and `int` have different sizes.
=> Use `%d` to log `int` value in `radius_server_receive_auth()` (fix for 32-bit OSes)

src/capture/middlewares/cleaner_middleware/cleaner_middleware.c
Use the `PRIu64` macro from [`<stdint.h>`](https://en.cppreference.com/w/c/types/integer) instead of `"%llu"` to log `uint64_t` values.
I believe every modern OS still uses 64-bit for `long long unsigned int`, so this shouldn't change anything.
=> Use `PRIu64` to format `uint64_t` values in `cleaner_middleware.c`

src/edgesec-recap.c
We should be using `PRIu32` instead of `"%llu"` to format `uint32_t` variables, as on pretty much all platforms, `unsigned long long` are `uint64_t`.
=> Use `PRIu32` to format `uint32_t` values in `process_pkt_header_state()`

lib/eloop/patches/0003-Bump-timeout-parameters-from-int-to-long.patch, lib/eloop/patches/0004-list-add-missing-include-on-stdddef.h.patch, lib/eloop/patches/0005-eloop-add-edge_-prefix-to-all-external-funcs.patch
We need to be using `"%lu"` instead of `"%u"` in the `eloop_register_timeout()` log message, since we changed the `eloop_register_timeout()` function to take a `unsigned long` instead of just a plain `unsigned int`.
Please note that the patch file calls the function `eloop_register_timeout ()` instead of `edge_eloop_register_timeout()`, because it's only renamed in [a later patch](https://github.com/nqminds/edgesec/blob/674b1feb9e4eb845405fccd53386466ed938136c/lib/eloop/patches/0005-eloop-add-edge_-prefix-to-all-external-funcs.patch)
---
@mereacre, if you want to view the updated patch/commit in GitHub's UI, here's a link: https://github.com/nqminds/hostap/commit/179c491f0b761207edd2b72870792af3fee55350
=> Use `%lu` to log `unsigned long` value in `edge_eloop_register_timeout()`

src/utils/log.h
In `src/utils/log.h`, there is a currently unused macro (since https://github.com/nqminds/edgesec/commit/2a18535cb57f7059dba72eb50490bda587291fe8) called `PRINTF_FORMAT` that can be used to tell compilers that a given function passes arguments to `printf`.
https://github.com/nqminds/edgesec/blob/8cd691957f4b727f81d08a0e452caf22102de317/src/utils/log.h#L40-L44
This syntax is `__attribute__((format(printf, (a), (b))))`, and is supported by GCC and Clang. [^1]
See https://clang.llvm.org/docs/AttributeReference.html#format
This PR adds documentation to the macro, adds support for this macro to Clang, and then marks all the `log_*` functions in `src/utils/log.h` with the macro.
[^1]: `__attribute((format` is even supported by the [ARM compiler][1] and [IBM C/C++ compiler][2].
[1]: …
=> Mark `log_*()` functions with `__attribute__((format))` for improved compiler warnings

src/edgesec-recap.c, src/edgesec.c, src/supervisor/subscriber_events.h
Mark more functions with `PRINTF_FORMAT`, so that the compiler knows it takes a format string as an input, and warns us if we use an invalid format string.
As discussed in https://github.com/nqminds/edgesec/pull/501#issuecomment-1458144372
=> Add the `PRINTF_FORMAT` attribute to more functions for improved compiler warnings

src/utils/sockctl.c
Considering I made this commit on a Monday, I'm going to assume it was because I was using the weak keyboard in the office, instead of a super nice mechanical keyboard from home. :smile:
I wonder if it's worth enabling something like [codespell](https://github.com/codespell-project/codespell). It easily integrates with `pre-commit, so it should be pretty easy to run. The only issue is fixing all the false positives.
=> docs(sockctl): fix typo in comment

CMakeModules/CodeCoverage.cmake
Update our `CodeCoverage.cmake` with the latest changes from upstream (aka https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake).
This is required for GCC compatibility, since the current `CodeCoverage.cmake` throws an error if we are using GCC, but not using GXX.
I did some investigating, and it looks like when our `CMakeModules/CodeCoverage.cmake` file was added in https://github.com/nqminds/edgesec/commit/acea20c1be2b5aae31c4a26b381a8b584a8462c7, this was equivalent to commit https://github.com/bilke/cmake-modules/commit/d98828f54f6974717798e63195cfbf08fe2daad0.
Then, I took the patches from https://github.com/bilke/cmake-modules/commit/d98828f54f6974717798e63195cfbf08fe2daad0 until https://github.com/bilke/cmake-modules/commit/877bab9dd1b17468c5d939cacaa2ad7ba99d1977 …
=> Update `CodeCoverage.cmake` with upstream changes

.github/workflows/create-debs.yml
This delay was here in an attempt to avoid race-conditions from running the tests twice in close succession.
However, since commit https://github.com/nqminds/edgesec/commit/ef3e689eef48f24289dcc094fc3bf8b5527f6da8 (PR https://github.com/nqminds/edgesec/pull/345), we're only running these tests once, so we might as well remove this delay and have faster CI runs.
=> ci(test): remove delay for code-coverage

lib/libnetlink/CMakeLists.txt
By default, when we call `project()` without any `LANGUAGES` in libnetlink's `CMakeLists.txt` file, CMake defaults to `C` and `C++`, see https://cmake.org/cmake/help/latest/command/enable_language.html
Since libnetlink only uses C code, we should explicitly say that it only uses C, so that we can remove it's dependency on C++.
=> build(libnetlink): remove C++ requirement

src/capture/middlewares/protobuf_middleware/protobuf_encoder.h
Fix the Doxygen `dir` attribute in `@param` command in the `protobuf_encoder.h` file.
See https://www.doxygen.nl/manual/commands.html#cmdparam
=> docs(protobuf_encoder): fix `@param` `dir` attr

CMakeLists.txt, lib/openssl.cmake
EDGESec only uses C code, so we don't need to get CMake to search for a C++ compiler [^1].
See https://askubuntu.com/a/1211755
OpenSSL still expects a CXX value, but it's not used for the OpenSSL build we compile, so we can just set it to an executable that does not exists. This is so we do start to use C++ in OpenSSL (e.g. due to a future OpenSSL update), we should instantly get an error.
[^1]: This occasionally causes issues with Clang, since `clang++` fails to compile a test program due to a missing `libstdc++`, because even though I have `g++-11` installed (and therefore `libstdc++-11-dev`), Clang sees that I have `gcc-12` installed, and incorrectly assumes that means I have `g++-12` (and GNU's `libstdc++-12-dev`) installed.
=> Remove dependency on C++

src/utils/CMakeLists.txt, src/utils/os.c, src/utils/os.h, tests/utils/CMakeLists.txt, tests/utils/test_os.c
Fix `edge_os_get_reltime()` so that it correctly gets the relative time.
It does this by using the [POSIX `CLOCK_MONOTONIC`][1], which defines a monotonic clock that never goes backwards.
Because `CLOCK_MONOTONIC` is not supported on all POSIX platforms, as backup we can use `CLOCK_REALTIME`, which is the same behavior as edge_os_get_time() (aka the old behavior).
[1]: https://pubs.opengroup.org/onlinepubs/000095399/functions/clock_getres.html
Fixes https://github.com/nqminds/edgesec/issues/408
=> fix(os): fix `edge_os_get_reltime()`

tests/test_runctl.c
Fix a heap overflow error in `test_run_engine()`, when we weren't allocating enough bytes for a `struct radius_server_data`.
---
We may want to consider adding `__attribute__((alloc_size (1))` to the `os_zalloc()` function to tell the compiler that it returns the number of bytes given by the `size` parameter.
I think compilers/static analysers should hopefully warn us then about [CWE-131: Incorrect Calculation of Buffer Size](https://cwe.mitre.org/data/definitions/131.html).
For example, GCC has `-Wanalyzer-allocation-size` that would warn us.
=> test(runctl): fix radius_server_data heap overflow

tests/supervisor/test_supervisor.c
Fix a memory leak in `test_get_mac_conn_cmd()`.
`open_sqlite_macconn_db()` was run to create `ctx.macconn_db`, but it was never cleaned up.
https://github.com/nqminds/edgesec/blob/85ae0cfb19dd1d545dd917a473b42459e5c4b5cf/tests/supervisor/test_supervisor.c#L59
=> test(supervisor): fix  `get_mac_conn_cmd()` mem leak

src/utils/sqliteu.c
We were not finalizing the `res` variable form `sqlite3_prepare_v2()` when `sqlite3_bind_text()` failed.
=> fix(sqliteu): fix memory leak in `check_table_exists()`

tests/utils/test_sqliteu.c
I accidentally used `'\n'` (newline character) to terminate my string instead of a `'\0'` (NUL character) 🤦.
Fixes: faa7aeb29d08c65c770c1056ba63b405ac9738a4
=> test(sqliteu): fix stack buffer overflow in test

src/config.c
The `value` pointer was already allocated at the beginning of the function at https://github.com/nqminds/edgesec/blob/6a0508ec7967b92fba133453e0ec496fadf1ccae/src/config.c#L228
---
We're doing a lot of `free(value);` and `value = malloc(...);`. We should probably refactor this function to avoid all of these duplicate calls, since calling `malloc()` is expensive.
=> fix(config): fix `load_radius_conf()` memory leak

src/edgesec.c
Make all functions in `edgesec.c` `static` (and file-scoped variables), since they are never used outside of this file.
The CHERI LLVM compiler is currently throwing an error when compiling edgesec for CHERI RISCV-purecap (probably due to a compiler/linker bug). It seems to be some sort of linker error due to the `log_lock_fun` function.
By making the `log_lock_fun` `static` (i.e. giving it internal linkage), this should hopefully mean that the linker never has to look at the function, so it should avoid this issue.
I've also removed the `get_app_name()` and `sighup_handler()` functions from `edgesec.c`, since they're no longer used (and making them `static` throws an unused function error).
=> Make functions and variables in `edgesec.c` `static`

src/config.h, tests/test_edgesec.c
Some of the values in `config` were allocated on the heap by `load_app_config()`:
https://github.com/nqminds/edgesec/blob/cbd6701393d7cd5ff3b134fb46056f206e2704b9/tests/test_edgesec.c#L350
Because of that, we must call `free_app_config()` to deallocate this variables.
---
Should we document this in the `load_app_config()` documentation?
https://github.com/nqminds/edgesec/blob/429d6179ec00553fe1959c105fb6dcb9a3ea4018/src/config.h#L86
=> test(edgesec): fix `test_edgesec()` config memory leak

tests/test_runctl.c
`test_init_context()` in `test/test_runctl.c` creates `ctx->config_ifinfo_array`, but it's never deallocated.
In fact, it's even allocated twice to the same variable.
**Allocated here**:
- https://github.com/nqminds/edgesec/blob/8e2f61a9287e16998998ab91fd0e4a9d983cccc2/tests/test_runctl.c#L152
- https://github.com/nqminds/edgesec/blob/e940f3a613585f5be2a7ad4dbf6f3618ee1cf616/tests/test_runctl.c#L172
I've removed the extraneous allocation, and added a `utarray_free(context.config_ifinfo_array);` at the end of the test function to fix this memory leak.
---
Side-note, the cleanup code for a `struct supervisor_context` and `struct app_config` is currently a bit messy. Can we somehow refactor this into cleanup functions?
- https://github.com/nqminds/edgesec/blob/8e2f61a9287e16998998ab91fd0e4a9d …
=> test(runctl): fix `test_init_context()` memory leak

tests/supervisor/test_supervisor.c
Currently, both the `ctx.vlan_mapper` and `ctx.mac_mapper` variables are allocated in `test_get_mac_conn_cmd()` and are never deallocated.
It looks like `ctx.vlan_mapper` is never used in this test, so I've removed the `create_vlan_mapper(ctx.config_ifinfo_array, &ctx.vlan_mapper);` call.
I've added `free_mac_mapper(&ctx.mac_mapper);` to the end of the of the test to free the `ctx.mac_mapper` variable.
=> Fix memory leaks in `test_get_mac_conn_cmd()`

src/utils/iface_mapper.c
Fix buffer overflows using the `ifname` parameter in the following functions in `src/utils/iface_mapper.c`:
- `get_if_mapper()`
- `put_if_mapper()`
Currently, we're using `os_memcpy(ifname, s->value, IF_NAMESIZE);` to copy the string from `ifname`. This is fine if `ifname` is at least IF_NAMESIZE bytes, but it's instead a NUL-terminated string that may be less than IF_NAMESIZE bytes long. In that case, we must only read up to `strlen(ifname)` bytes.
This can be fixed by replacing the `memcpy()` calls with `os_strlcpy()` (edgesec's implementation of [BSD strlcpy()](https://man.freebsd.org/cgi/man.cgi?query=strlcpy&sektion=3) function).
=> Fix buffer overflow with ifname in `iface_mapper`

tests/ap/test_ap_service_failure.c
Fix a memory leak in the `__wrap_writeread_domain_data_str()` function, that mocks `writeread_domain_data_str()`.
If the return code of `writeread_domain_data_str()` is non-0, the caller will **NOT** deallocate the reply pointer.
Because of that, we must only allocate the reply string if the return code is 0.
=> Fix the `writeread_domain_data_str()` mock in `test_ap_service_failure.c`

.cirrus.yml
Currently, a bunch of the edgesec tests fail on FreeBSD. Because of that, we have a `FAILING_TESTS` of tests that we expect to fail when running Cirrus CI:
https://github.com/nqminds/edgesec/blob/8e2f61a9287e16998998ab91fd0e4a9d983cccc2/.cirrus.yml#L25-L27
This is so:
1. CI throws an error if any test fails that isn't listed in `FAILING_TESTS`
2. CI throws an error if any test succeeds and it is listed in `FAILING_TESTS`
Our current implementation uses some complicated regex and runs ctest multiples times.
However, we want to add a [`cheribuild`](https://github.com/CTSRD-CHERI/cheribuild) action to CI, and they don't support passing regexes to `ctest`.
Additionally, this new implementation should be a lot faster, since instead of calling `ctest` multiple times, we only call it a single …
=> ci(cirrus): improve how failing tests are checked

.cirrus.yml
Add a test in [Cirrus CI][1] that tries to build edgesec for the [CHERIBSD][2] operating system with the [Morello Purecap][3] CHERI architecture.
To do this, we use [cheribuild][4], with a Docker image called [`aloisklink/cheribuild-edgesec`][5] that has all of the common SDK (like LLVM/CMake/QEMU emulator) pre-built.
[1]: https://cirrus-ci.org/
[2]: https://github.com/CTSRD-CHERI/cheribsd
[3]: https://www.morello-project.org/
[4]: https://github.com/CTSRD-CHERI/cheribuild
[5]: https://hub.docker.com/r/aloisklink/cheribuild-edgesec
Running these tests is pretty fast: it takes about 18 minutes in total to do a complete run (this is compared to the 8-10 minutes that a normal build takes on GitHub Actions).
> ![image](https://user-images.githubusercontent.com/19716675/225092688-7fc8c858-79fa- …
=> Compile and test for cheribsd-morello-purecap using Cirrus CI

src/runctl.c, tests/test_edgesec.c
Skip `free()`-ing the `eloop` parameter in `run_ctl()`. If this parameter is passed in to `run_ctl()`, we should let the caller `free()` it instead of us.
This also fixes a memory leak in `test_edgesec.c`.
---
I've also simplified the `run_ctl()` cleanup code by merging the success and `goto run_engine_fail` code.
The only two differences between the two was:
1. the success bit `return 0`, while the failure bit `return -1;`, which was easy to fix.
2. On the success bit, this following line of code was always call:
https://github.com/nqminds/edgesec/blob/b722d492217a769f0e86904fb0ceac7f92212940/src/runctl.c#L584
However, on the `goto run_engine_fail` branch, it was hidden behind an `if (.. != NULL)` branch:
https://github.com/nqminds/edgesec/blob/b722d492217a769f0e86904fb0ceac7f92212940/src …
=> Fix a potential double-`free()` in `run_ctl()`

src/capture/middlewares/pcap_middleware/CMakeLists.txt, src/capture/middlewares/pcap_middleware/pcap_queue.h
Document that `free_pcap_queue()` must be used to cleanup the `struct pcap_queue*` returned by `init_pcap_queue()`.
If supported (GCC >= 11), I've also added a `__attribute__((malloc(free_pcap_queue, 1)))` to the `init_pcap_queue()` function, so that the compiler knows to warn us if we use the wrong deallocator.
---
This commit has been on my local machine for a while, so I can't exactly remember why I made this change. Maybe I've encountered a memory leak bug in another WIP branch? Still, adding more documentation is always a good thing.
=> docs(pcap_queue): doc using free_pcap_queue()

src/crypt/CMakeLists.txt, src/crypt/crypt_service.c, src/crypt/crypt_service.h, tests/supervisor/test_supervisor.c
The `test_get_mac_conn_cmd` test in `test_supervisor.c` was not correctly cleaning up the `ctx.crypt_ctx` object, when we were compiling tests with `WITH_CRYPTO_SERVICE=ON`.
We should be using `free_crypt_service()` to avoid a memory leak.
Fixes: https://github.com/nqminds/edgesec/commit/0913b22966baa4f0ef7c1518fc636e2a534b565d
---
In order to prevent this from happening again, I've added documentation to the `load_crypt_service()` function to say that `free_crypt_service()` should be called on the result. If we're compiling with GCC >= 11, I've also added the `__attribute__((malloc(free_crypt_service, 1)))` compiler attribute to `load_crypt_service()`, so that the compiler warns us if we use the wrong deallocator.
=> Cleanup `ctx.crypt_ctx` correctly by calling `free_crypt_service()`

tests/capture/middlewares/test_protobuf_utils.c
Fix two memory leaks in the `test_protobuf_c_message_del_pack()` test function.
I've also improved the documentation in the `serialize_protobuf` function and made it `static`, since we never use it outside of this test file.
=> test(protobuf_utils): fix mem leak in test

tests/utils/test_uci_wrt.c
Fix the memory leaks in the `uci_wrt` tests.
---
Unfortunately we can't add an `__attribute__((malloc(utarray_free, 1)))` attribute to the `uwrt_get_interfaces` function to help prevent this from happening again, because `utarray_free()` isn't a function, it's a pre-processor macro.
https://github.com/nqminds/edgesec/blob/71d2dcdb39478e532d3b6d62dc3c587b9d5177b1/tests/utils/test_uci_wrt.c#L70
=> test(uci_wrt): fix memory leaks in `uci_wrt` tests

src/utils/CMakeLists.txt, src/utils/log.c
Make the `src/utils/log.c` file compile under standard POSIX C by removing the BSD-only `gettimeofday()` function.
Instead, we can use `timespec_get()`, which is part of the ISO C11 standard, and gets the time with up to nanosecond precision.
---
Other changes to `time_to_str()`:
- This function only ever returns one value, that's never checked, so we can remove
it and make its return-type `void`
- This function is never called outside of this file, so we might as well make it
`static`.
- The input buffer must be at least 25 bytes large, so we might as
well mark it as `char buf[static 25]`.
- I've also added an error handler for a Y2K38 overflow on 32-bit
machines. I believe `gettimeofday()` will also overflow on 32-bit machines, but :shrug:, it's not a standard function so documentation …
=> Make `src/utils/log.c` compliant with the POSIX C standard

CMakeLists.txt, CMakePresets.json
Compile edgesec tests with the [`-fsanitize=address` flag](https://clang.llvm.org/docs/AddressSanitizer.html) which enables [AddressSanitizer (aka ASan)](https://github.com/google/sanitizers/wiki/AddressSanitizer).
> [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) (aka ASan) is a memory error detector for C/C++. It finds:
> 
> - [Use after free](https://github.com/google/sanitizers/wiki/AddressSanitizerExampleUseAfterFree) (dangling pointer dereference)
> - [Heap buffer overflow](https://github.com/google/sanitizers/wiki/AddressSanitizerExampleHeapOutOfBounds)
> - [Stack buffer overflow](https://github.com/google/sanitizers/wiki/AddressSanitizerExampleStackOutOfBounds)
> - [Global buffer overflow](https://github.com/google/sanitizers/wiki/AddressSanitizerExam …
=> Compile and test linux presets with AddressSanitizer to catch memory issues

src/utils/cryptou.c
Define [OPENSSL_API_COMPAT][1] and [OPENSSL_NO_DEPRECATED][2] macros before including OpenSSL headers to prevent including OpenSSL functions that are deprecated since Since OpenSSL 1.1.1.
OpenSSL 1.1.1 is the minimum version of OpenSSL we support, as it's the version in:
- [Ubuntu 20.04 LTS ("focal")][3]
- [Debian 10 ("buster")][4]
[1]: https://www.openssl.org/docs/man3.0/man7/OPENSSL_API_COMPAT.html#OPENSSL_API_COMPAT
[2]: https://www.openssl.org/docs/man3.0/man7/OPENSSL_API_COMPAT.html#OPENSSL_NO_DEPRECATED
[3]: https://packages.ubuntu.com/it/focal/libssl-dev
[4]: https://packages.debian.org/buster/libssl-dev
---
This flag caught two functions that are deprecated in OpenSSL 1.1.1: `X509_get_notBefore` and `X509_get_notAfter`
I've replaced them with the similar `X509_getm_notBefore` and …
=> Enable `OPENSSL_API_COMPAT` and remove all functions deprecated in OpenSSL 1.1.1

CMakeLists.txt, CMakePresets.json
Enable [UndefinedBehaviorSanitizer (UBSan)][1] on Linux presets by default.
> UndefinedBehaviorSanitizer (UBSan) is a fast undefined behavior detector. UBSan modifies the program at compile-time to catch various kinds of undefined behavior during program execution, for example:
> 
> - Array subscript out of bounds, where the bounds can be statically determined
> - Bitwise shifts that are out of bounds for their data type
> - Dereferencing misaligned or null pointers
> - Signed integer overflow
> - Conversion to, from, or between floating-point types which would overflow the destination
The OpenWRT SDK presets have it disabled, as old versions of GCC have poor support for running UBSanitizer on non-x86 platforms.
[1]: https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
=> build(cmake): enable UndefinedBehaviorSanitizer

src/dns/command_mapper.c, src/dns/command_mapper.h
Make the `put_command_mapper()` and `check_command_mapper()` use a `const` string as an input parameter.
I've also made the `hmap` param to `check_command_mapper()` partially `const`, since we never modify it.
=> refactor(command_mapper): make functions `const`

src/utils/os.c, src/utils/os.h
Make `read_file_string()`'s `path` param `const`, since we don't change it in the function.
=> refactor(os): make `read_file_string()` param const

src/utils/os.c, src/utils/os.h
Make all the function parameters in `src/utils/os.c` `const` when possible.
This changes the following functions:
- `is_proc_running()`
- `signal_process()`
- `os_strnlen_s()`
- `os_reltime_before()`
- `os_reltime_sub()`
- `check_file_exists()`
- `check_sock_file_exists()`
I've also documented that the `get_hostname()` might not return a NUL-terminated C-string if `gethostname()` returns a hostname that is exactly `OS_HOST_NAME_MAX` bytes long.
This is the behavior of `gethostname()` on GNU C library, see [`man gethostname(2)`](https://man7.org/linux/man-pages/man2/sethostname.2.html).
=> Make function parameters in `os` `const` when possible

.cirrus.yml, src/dhcp/dnsmasq.c, src/dhcp/dnsmasq.h
Make the `dhcp_bin_path` parameter to `signal_dhcp_process()` `const`.
Because we call `basename()` on this value, which may change the input string, we need to first make a temporary copy of the string into a buffer.
=> refactor(dnsmasq): make `signal_dhcp_process()` const

.cirrus.yml, tests/dns/test_mdns_service.c
The `struct mdns_context context` data was not initialized when it was used in `test_run_mdns` and `test_close_mdns`.
On Linux, this wasn't a problem, since the memory just happened to be initialized to NULL, but on FreeBSD, the memory was filled with garbage, which causes a Segmentation fault when trying to run `init_reflections()` on a garbage pointer.
Fixes the `test_mdns_service` on FreeBSD.
---
Should we maybe instead use `init_mdns_context` to initialize this context instead of 0-initializing it? The only issue is that this function is currently not in any `.h` header file, so we can't easily test it :shrug: https://github.com/nqminds/edgesec/blob/780f2b76bb8293471c252370e8dbaf3208d13e8a/src/dns/mdns_service.c#L729-L732
=> Fix `test_mdns_service` on FreeBSD due to uninitialized data in test

src/CMakeLists.txt, src/config.c, src/dhcp/CMakeLists.txt, src/dhcp/dhcp_config_utils.c, src/dhcp/dhcp_config_utils.h, tests/dhcp/CMakeLists.txt, tests/dhcp/test_dnsmasq.c
In edgesec, we have two slightly different definitions of `get_config_dhcpinfo()`, in:
- https://github.com/nqminds/edgesec/blob/da4f33eb7377563e02b032398f52a4f21fc570a2/src/config.c#L32-L84
- https://github.com/nqminds/edgesec/blob/da4f33eb7377563e02b032398f52a4f21fc570a2/tests/dhcp/test_dnsmasq.c#L165-L221
This PR proposes replacing these two definitions with a single definition in a new file called `src/dhcp/dhcp_config_utils.c`.
Minor differences:
- I've taken the definition from the `src/config.c` file. The one in `tests/dhcp/test_dnsmasq.c` was almost exactly the same, except it had a bunch of `log_trace()` commands, which I removed.
- I've made the `info` parameter `const` since we only read from it.
=> Move `get_config_dhcpinfo()` function into `src/dhcp/dhcp_config_utils.c`

.cirrus.yml, CMakePresets.json
Compile and test with [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) and [UndefinedBehaviorSanitizer (UBSan)](https://www.chromium.org/developers/testing/undefinedbehaviorsanitizer/) on FreeBSD.
See PRs https://github.com/nqminds/edgesec/pull/540 and https://github.com/nqminds/edgesec/pull/541 which enabled these sanitizers for Linux for more information on why we want them.
Since on FreeBSD, [ASLR (Address Space Layout Randomization)](https://wiki.freebsd.org/AddressSpaceLayoutRandomization) is enabled by default, (see the below error message), we need to use [`proccontrol`][1] to disable ASLR for the process.
> This sanitizer is not compatible with enabled ASLR and binaries compiled with PIE
[1]: …
=> Compile and test with Address/UndefinedBehaviorSan on FreeBSD
