nqminds/edgesec

README.md

leave better breadcrumb to installation instructions that disappeared

---

src/dhcp/dnsmasq.h
tests/dhcp/test_dhcp_service.c
tests/dhcp/test_dnsmasq.c
tests/dns/CMakeLists.txt

Fix the failing DNS/DHCP tests.
I needed a confirmed working config, before I started modifying all the cmake jazz.

Fix DHCP tests

---

CMakeModules/install.cmake
debian/rules
src/CMakeLists.txt
tests/test_engine.c

I think this should fix the GitHub Action :)
**Let's wait to see if it passes with a green tick before merging.**

Fix debuild to use ubuntu CMake config

---

CMakeLists.txt
CMakePresets.json
src/capture/capture_service.c
src/capture/capture_service.h
src/capture/cleaner_middleware/cleaner_middleware.c
src/capture/header_middleware/CMakeLists.txt
src/supervisor/CMakeLists.txt
src/utils/iptables.h
src/utils/os.h
tests/CMakeLists.txt

- Integrated all @aloisklink pull requests
- Translated from running processes to running threads
- Loads of refactoring
@aloisklink could you please check if all of it compiles on owrt and maybe if you find some other optimizations in cmake that we need to do?

Thread transform

---

src/runctl.c

Fixes a C compiler warning in `close_capture_thread`.
For some reason, the C compiler thought that `current->value.capture_pid` was a pointer type,
and was printing a warning on my PC about comparing a pointer type using `> to and int `0`.
I'm guessing maybe `HASH_ITER` was causing some weird behaviour with the C compiler?
Maybe `pthread_t` has a pointer type in OpenWRT or something, since the docs say that the structure is purposely never described :shrug: 
> ```c
> /* Thread identifiers.  The structure of the attribute type is not
>    exposed on purpose.  */
> typedef unsigned long int pthread_t;
> ```
> From my local `/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h`
I've changed the loop (since `HASH_ITER` should only be used if you're deleting data, see …

refactor: tidy up close_capture_thread

---

deployment/owrt-config/ISSUES.md

Documents some issues we had with OpenWRT, and potential fixes to them.

Create OpenWRT ISSUES.md

---

debian/copyright
src/utils/iface.h
src/utils/iface_mapper.h
src/utils/list.h
src/utils/nl.h
src/utils/os.h
src/utils/sockctl.h
src/utils/squeue.h
src/utils/uci_wrt.h

Fixes some errors from doxygen.
Most of these are just basic typos.

Fix some doxygen errors

---

CHANGELOG.md
README.md
debian/changelog

Added changelog update for 0.0.8

Added changelog update for 0.0.8

---

tests/utils/test_os.c

`test_list_dir()` was assuming that uname existed in `/bin/uname`, which is part of the [Linux FSSTND/FHS][1].
However, on FreeBSD, `uname` actually exists under `/usr/bin/uname`. To fix this, instead we search for `/bin/ls`, which should exist for almost every POSIX distribution.
Related to https://github.com/nqminds/edgesec/commit/eeacd62e4fa02b66b6dc6912816210fc273e20a5
[1]: https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/bin.html

test(os): support freebsd for test_list_dir()

---

tests/ap/test_hostapd.c

I've also slightly upgraded the tests to make it easier to see where any differences in the strings are.

test(hostapd): fix unused var in openwrt tests

---

src/utils/ipgen.c
src/utils/ipgen.h
src/utils/os.c
src/utils/os.h

Nothing special, just `const` :)

Added const qualifiers

---

src/utils/net.c
src/utils/net.h
src/utils/sockctl.c
src/utils/sockctl.h

Refactors the `sockctl` files.
This PR mainly just improves documentation, and adds `const` to as many params as I can (as it was breaking some other code that I was working on).
However, there is a small bug fix, performance fix, and some refactoring that I also did.
I'd recommend reviewing commit by commit to make things more manageable.

Cleanup sockctl files

---

src/utils/net.c
src/utils/net.h
src/utils/nl.c
src/utils/nl.h

Makes the params of some functions in `nl` and `net` `const`.

nl and net const improvements

---

tests/supervisor/test_supervisor.c

Fix segmentation fault due to uninitialized `crypt_ctx`.
---
It might also be worth adding `if (crypto_ctx == NULL) {log_error("crypto_ctx == NULL"); return -1;}` to some functions.

test(supervisor): fix segmentation fault

---

src/capture/middlewares/protobuf_middleware/protobuf_middleware.c

Close the named pipe by the thread.

fix: Close the pipe

---

src/utils/squeue.c
src/utils/squeue.h

**DRAFT UNTIL #265 IS MERGED**
(we may also need to refresh the PR so that all of the PR #265 commits disappear)
The current `src/utils/list.h` does not work with this PR, however newer versions of `list.h` contain commit https://w1.fi/cgit/hostap/commit/src/utils/list.h?id=2a7023ba6f4ef318f52efbd52c9f54459c06d6cb which fixes the `list.h` file.
---
Make params to the `squeue` functions `const` when possible.
I've also improved the documentation, to clarify what are input/output params, and when output params must have `free()`-ed.

refactor(squeue): make squeue params const

---

src/ap/ap_service.h
tests/ap/CMakeLists.txt
tests/ap/test_ap_service.c
tests/ap/test_ap_service_failure.c

Adds a bunch more tests to `ap_service` to fix #394.

test(ap_service): more tests for ap_service

---

src/utils/hashmap.c

Use `HASH_REPLACE_STR()` in `hmap_str_keychar_put()`.
This is slightly less efficient (because we are calling `malloc()` twice instead of once), but the code is much simpler and it matches the docs of uthash, see:
> HASH_REPLACE macros are equivalent to HASH_ADD macros except they attempt to find and delete the item first. If it finds and deletes an item, it will also return that items pointer as an output parameter.
>
> _Taken from https://troydhanson.github.io/uthash/userguide.html#_replace_item_

refactor(hashmap): use HASH_REPLACE_STR

---

src/supervisor/cmd_processor.c

Handle `ENOMEM` errors when allocating memory on the heap in the function `process_get_bridges_cmd()`.
This is required to avoid memory leaks and accessing NULL pointers (which is undefined behaviour).

Handle `ENOMEM` error in `process_get_bridges_cmd()`

---

tests/utils/test_eloop_threaded.c

The code-coverage on `eloop_destroy()` is currently inconsistent.
This is because there is a branch that only runs `if (timeout->time.usec < now.usec) {`, where `now` is created from `os_get_reltime()`.
I've made a test that checks for `eloop_destroy()` using a timeout that has a `usec` of `0`.
Because there's a 1-in-a-million chance that `now.usec` is 0, I'm running this test twice with a 1 microsecond delay, so that this branch should always be hit.

test(eloop): test `eloop_destroy()`
